= When is a Blockchain compelling
Peter Lawrey
:published_at: 2018-04-16
:hp-tags: Block Chain, Use Case

I was recently asked; when is using a Blockchain really needed?

IMHO the main benefit is **ease of provider integration** Blockchain allows providers to join a system, with a much lower barrier to entry. If you are looking to build a network of new and innovative providers, which don't have to trust each other, instead they trust the protocol, a blockchain is a compelling solution.

=== When is Blockchain not a compelling reason?

First I feel I should debunk some reasons often stated

==== Blockchain doesn't make everything better

In many cases when a blockchain is proposed, it is used as little more than a log of changes in a database. In some cases, a distributed ledger could be used when a centralised database isn't enough. Blockchain projects are easier to get approved these days as companies and individuals want to improve their blockchain skill sets but this doesn't make it compelling from a technical point of view IMHO.

==== Blockchain is unlikely to make things faster

In most cases you will still need a database for reporting services, so adding a blockchain is highly likely to make it more complicated and slower, not simpler and faster than a database alone. https://www2.deloitte.com/nl/nl/pages/financial-services/articles/5-blockchain-use-cases-in-financial-services.html[To speed up a process] 

Blockchain can make a system faster if it can replace enough of an existing system which already implements the features a blockchain offers but in a less efficient manner.

==== Blockchain does address all security concerns

To compromise a cluster of nodes you can employ a https://learncryptography.com/cryptocurrency/51-attack[51% attack]. If you control a majority of nodes, you control the whole system.  This could happen by adding or hacking enough nodes. A state level organisation could do this, potentially even with the most popular crypto currencies, however most govenments have easier/cheaper ways of exercising policy or influence.

Many cryptocurrencies are public which is a real privacy concern when some of the bank balances are very high (or at least high to the individuals holding them) 

At the time of writing https://bitinfocharts.com/bitcoin/address/3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r[This bitcoin address] has $1.5 bn, and this https://etherscan.io/address/0x281055afc982d96fab65b3a49cac8b878184cb16[ethereum address] has around $770 m which makes them targets for hackers and organised crime.  

Making this information private is likely to be highly desirable. However it could still be obtained through a hack though that is harder.

=== When is Blockchain compelling?

When participants trust a protocol, they don't have to trust each other as much. This makes inclusion of new participants easier and allow existing ones to be more innovative.

==== Security

Reduced security impacts via a https://www.forbes.com/sites/bernardmarr/2017/08/10/practical-examples-of-how-blockchains-are-used-in-banking-and-the-financial-services-sector/[immutable ledger] This means a new provider can joins without all the existing providers needing to be fully comfortable with their security setup. 

NOTE: A high percentage of hacks involve disgruntled former employees. If you trust every node from every provider you have to trust every person operating it.

==== Innovative solutions

Using sub-chains, different providers can offer innovative solutions, without every one else in the system needing to be comfortable with those solutions. By the time every participant is comfortable with a new solution, it probably not that innovative/disruptive. If every node needs to be trusted, how can't offer a solution/transaction type unless every provider is comfortable with the risk associated with it.

==== Built in fee support

As the system controls the flow of value, it can also include settlement of fees and cut off participants. e.g. if a participant, for what ever reason, starts spamming the system, this will cost them and result in them being cut off.

=== Does a blockchain need to have it's own currency?

A blockchain offers a virtualised currency.  This can be one backed by fiat or another digital currency, or it's own currency or both.  If the system has fees to cover the cost of running the service, it needs to be in a supported currency.  This could be in USD or EUR rather a new currency, however a crypto currency has the advantage that the actual cost can have a floating exchanging rate with fiat currencies. e.g. each transaction could cost 1 TXN and the value of this can be determined by an exchange.

=== Conclusion

While I feel than many blockchain soltuions could have used a database instead, there are some compelling use cases which allow multiple providers to offer innovating solutions to customers.

