= String.hashCode() is not even a little unique
Peter Lawrey

Some have a misconception that a 32-bit hashCode() can be unique for even complex data. Many realise that String.hashCode() is not unique, but might not realise how bad it is. While it is true that all one character Strings have a unique hashCode, this breaks down for two character Strings.

=== Two character ASCII strings with common hashCodes

[separator=¦]
|===
¦ hashCode() ¦ String 1 ¦ String 2 ¦ String 3 ¦ String 4
¦ 1149 ¦ !~ ¦ "_ ¦ #@ ¦ $!
¦ 1180 ¦ "~ ¦ #_ ¦ $@ ¦ %!
¦ 1211 ¦ #~ ¦ $_ ¦ %@ ¦ &!
¦ 1242 ¦ $~ ¦ %_ ¦ &@ ¦ '!
¦ 1273 ¦ %~ ¦ &_ ¦ '@ ¦ (!
¦ 1304 ¦ &~ ¦ '_ ¦ (@ ¦ )!
¦ 1335 ¦ '~ ¦ (_ ¦ )@ ¦ *!
¦ 1366 ¦ (~ ¦ )_ ¦ *@ ¦ +!
¦ 1397 ¦ )~ ¦ *_ ¦ +@ ¦ ,!
¦ 1428 ¦ *~ ¦ +_ ¦ ,@ ¦ -!
¦ 1459 ¦ +~ ¦ ,_ ¦ -@ ¦ .!
¦ 1490 ¦ ,~ ¦ -_ ¦ .@ ¦ /!
¦ 1521 ¦ -~ ¦ ._ ¦ /@ ¦ 0!
¦ 1552 ¦ .~ ¦ /_ ¦ 0@ ¦ 1!
¦ 1583 ¦ /~ ¦ 0_ ¦ 1@ ¦ 2!
¦ 1614 ¦ 0~ ¦ 1_ ¦ 2@ ¦ 3!
¦ 1645 ¦ 1~ ¦ 2_ ¦ 3@ ¦ 4!
¦ 1676 ¦ 2~ ¦ 3_ ¦ 4@ ¦ 5!
¦ 1707 ¦ 3~ ¦ 4_ ¦ 5@ ¦ 6!
¦ 1738 ¦ 4~ ¦ 5_ ¦ 6@ ¦ 7!
¦ 1769 ¦ 5~ ¦ 6_ ¦ 7@ ¦ 8!
¦ 1800 ¦ 6~ ¦ 7_ ¦ 8@ ¦ 9!
¦ 1831 ¦ 7~ ¦ 8_ ¦ 9@ ¦ :!
¦ 1862 ¦ 8~ ¦ 9_ ¦ :@ ¦ ;!
¦ 1893 ¦ 9~ ¦ :_ ¦ ;@ ¦ <!
¦ 1924 ¦ :~ ¦ ;_ ¦ <@ ¦ =!
¦ 1955 ¦ ;~ ¦ <_ ¦ =@ ¦ >!
¦ 1986 ¦ <~ ¦ =_ ¦ >@ ¦ ?!
¦ 2017 ¦ =~ ¦ >_ ¦ ?@ ¦ @!
¦ 2048 ¦ >~ ¦ ?_ ¦ @@ ¦ A!
¦ 2079 ¦ ?~ ¦ @_ ¦ A@ ¦ B!
¦ 2110 ¦ @~ ¦ A_ ¦ B@ ¦ C!
¦ 2141 ¦ A~ ¦ B_ ¦ C@ ¦ D!
¦ 2172 ¦ B~ ¦ C_ ¦ D@ ¦ E!
¦ 2203 ¦ C~ ¦ D_ ¦ E@ ¦ F!
¦ 2234 ¦ D~ ¦ E_ ¦ F@ ¦ G!
¦ 2265 ¦ E~ ¦ F_ ¦ G@ ¦ H!
¦ 2296 ¦ F~ ¦ G_ ¦ H@ ¦ I!
¦ 2327 ¦ G~ ¦ H_ ¦ I@ ¦ J!
¦ 2358 ¦ H~ ¦ I_ ¦ J@ ¦ K!
¦ 2389 ¦ I~ ¦ J_ ¦ K@ ¦ L!
¦ 2420 ¦ J~ ¦ K_ ¦ L@ ¦ M!
¦ 2451 ¦ K~ ¦ L_ ¦ M@ ¦ N!
¦ 2482 ¦ L~ ¦ M_ ¦ N@ ¦ O!
¦ 2513 ¦ M~ ¦ N_ ¦ O@ ¦ P!
¦ 2544 ¦ N~ ¦ O_ ¦ P@ ¦ Q!
¦ 2575 ¦ O~ ¦ P_ ¦ Q@ ¦ R!
¦ 2606 ¦ P~ ¦ Q_ ¦ R@ ¦ S!
¦ 2637 ¦ Q~ ¦ R_ ¦ S@ ¦ T!
¦ 2668 ¦ R~ ¦ S_ ¦ T@ ¦ U!
¦ 2699 ¦ S~ ¦ T_ ¦ U@ ¦ V!
¦ 2730 ¦ T~ ¦ U_ ¦ V@ ¦ W!
¦ 2761 ¦ U~ ¦ V_ ¦ W@ ¦ X!
¦ 2792 ¦ V~ ¦ W_ ¦ X@ ¦ Y!
¦ 2823 ¦ W~ ¦ X_ ¦ Y@ ¦ Z!
¦ 2854 ¦ X~ ¦ Y_ ¦ Z@ ¦ [!
¦ 2885 ¦ Y~ ¦ Z_ ¦ [@ ¦ \!
¦ 2916 ¦ Z~ ¦ [_ ¦ \@ ¦ ]!
¦ 2947 ¦ [~ ¦ \_ ¦ ]@ ¦ ^!
¦ 2978 ¦ \~ ¦ ]_ ¦ ^@ ¦ _!
¦ 3009 ¦ ]~ ¦ ^_ ¦ _@ ¦ `!
¦ 3040 ¦ ^~ ¦ __ ¦ `@ ¦ a!
¦ 3071 ¦ _~ ¦ `_ ¦ a@ ¦ b!
¦ 3102 ¦ `~ ¦ a_ ¦ b@ ¦ c!
¦ 3133 ¦ a~ ¦ b_ ¦ c@ ¦ d!
¦ 3164 ¦ b~ ¦ c_ ¦ d@ ¦ e!
¦ 3195 ¦ c~ ¦ d_ ¦ e@ ¦ f!
¦ 3226 ¦ d~ ¦ e_ ¦ f@ ¦ g!
¦ 3257 ¦ e~ ¦ f_ ¦ g@ ¦ h!
¦ 3288 ¦ f~ ¦ g_ ¦ h@ ¦ i!
¦ 3319 ¦ g~ ¦ h_ ¦ i@ ¦ j!
¦ 3350 ¦ h~ ¦ i_ ¦ j@ ¦ k!
¦ 3381 ¦ i~ ¦ j_ ¦ k@ ¦ l!
¦ 3412 ¦ j~ ¦ k_ ¦ l@ ¦ m!
¦ 3443 ¦ k~ ¦ l_ ¦ m@ ¦ n!
¦ 3474 ¦ l~ ¦ m_ ¦ n@ ¦ o!
¦ 3505 ¦ m~ ¦ n_ ¦ o@ ¦ p!
¦ 3536 ¦ n~ ¦ o_ ¦ p@ ¦ q!
¦ 3567 ¦ o~ ¦ p_ ¦ q@ ¦ r!
¦ 3598 ¦ p~ ¦ q_ ¦ r@ ¦ s!
¦ 3629 ¦ q~ ¦ r_ ¦ s@ ¦ t!
¦ 3660 ¦ r~ ¦ s_ ¦ t@ ¦ u!
¦ 3691 ¦ s~ ¦ t_ ¦ u@ ¦ v!
¦ 3722 ¦ t~ ¦ u_ ¦ v@ ¦ w!
¦ 3753 ¦ u~ ¦ v_ ¦ w@ ¦ x!
¦ 3784 ¦ v~ ¦ w_ ¦ x@ ¦ y!
¦ 3815 ¦ w~ ¦ x_ ¦ y@ ¦ z!
¦ 3846 ¦ x~ ¦ y_ ¦ z@ ¦ {!
¦ 3877 ¦ y~ ¦ z_ ¦ {@ ¦ |!
¦ 3908 ¦ z~ ¦ {_ ¦ |@ ¦ }!
¦ 3939 ¦ {~ ¦ |_ ¦ }@ ¦ ~!
|===

NOTE: When strings have the same hashCode and combination of them, of the same length appended together also have the same hashCode.

=== Three character strings with the most common hashCodes

[separator=¦]
|===
¦ 35652 ¦ !{~ ¦ !|_ ¦ !}@ ¦ !~! ¦ "\~ ¦ "]_ ¦ "^@ ¦ "_! ¦ #=~ ¦ #>_ ¦ #?@ ¦ #@! ¦ $!!
¦ 35683 ¦ !|~ ¦ !}_ ¦ !~@ ¦ "]~ ¦ "^_ ¦ "_@ ¦ "`! ¦ #>~ ¦ #?_ ¦ #@@ ¦ #A! ¦ $!@ ¦ $"!
¦ 35714 ¦ !}~ ¦ !~_ ¦ "^~ ¦ "__ ¦ "`@ ¦ "a! ¦ #?~ ¦ #@_ ¦ #A@ ¦ #B! ¦ $!_ ¦ $"@ ¦ $#!
¦ 35745 ¦ !~~ ¦ "_~ ¦ "`_ ¦ "a@ ¦ "b! ¦ #@~ ¦ #A_ ¦ #B@ ¦ #C! ¦ $!~ ¦ $"_ ¦ $#@ ¦ $$!
¦ 36613 ¦ "{~ ¦ "|_ ¦ "}@ ¦ "~! ¦ #\~ ¦ #]_ ¦ #^@ ¦ #_! ¦ $=~ ¦ $>_ ¦ $?@ ¦ $@! ¦ %!!
¦ 36644 ¦ "|~ ¦ "}_ ¦ "~@ ¦ #]~ ¦ #^_ ¦ #_@ ¦ #`! ¦ $>~ ¦ $?_ ¦ $@@ ¦ $A! ¦ %!@ ¦ %"!
¦ 36675 ¦ "}~ ¦ "~_ ¦ #^~ ¦ #__ ¦ #`@ ¦ #a! ¦ $?~ ¦ $@_ ¦ $A@ ¦ $B! ¦ %!_ ¦ %"@ ¦ %#!
¦ 36706 ¦ "~~ ¦ #_~ ¦ #`_ ¦ #a@ ¦ #b! ¦ $@~ ¦ $A_ ¦ $B@ ¦ $C! ¦ %!~ ¦ %"_ ¦ %#@ ¦ %$!
¦ 37574 ¦ #{~ ¦ #|_ ¦ #}@ ¦ #~! ¦ $\~ ¦ $]_ ¦ $^@ ¦ $_! ¦ %=~ ¦ %>_ ¦ %?@ ¦ %@! ¦ &!!
¦ 37605 ¦ #|~ ¦ #}_ ¦ #~@ ¦ $]~ ¦ $^_ ¦ $_@ ¦ $`! ¦ %>~ ¦ %?_ ¦ %@@ ¦ %A! ¦ &!@ ¦ &"!
¦ 37636 ¦ #}~ ¦ #~_ ¦ $^~ ¦ $__ ¦ $`@ ¦ $a! ¦ %?~ ¦ %@_ ¦ %A@ ¦ %B! ¦ &!_ ¦ &"@ ¦ &#!
¦ 37667 ¦ #~~ ¦ $_~ ¦ $`_ ¦ $a@ ¦ $b! ¦ %@~ ¦ %A_ ¦ %B@ ¦ %C! ¦ &!~ ¦ &"_ ¦ &#@ ¦ &$!
¦ 38535 ¦ ${~ ¦ $|_ ¦ $}@ ¦ $~! ¦ %\~ ¦ %]_ ¦ %^@ ¦ %_! ¦ &=~ ¦ &>_ ¦ &?@ ¦ &@! ¦ '!!
¦ 38566 ¦ $|~ ¦ $}_ ¦ $~@ ¦ %]~ ¦ %^_ ¦ %_@ ¦ %`! ¦ &>~ ¦ &?_ ¦ &@@ ¦ &A! ¦ '!@ ¦ '"!
¦ 38597 ¦ $}~ ¦ $~_ ¦ %^~ ¦ %__ ¦ %`@ ¦ %a! ¦ &?~ ¦ &@_ ¦ &A@ ¦ &B! ¦ '!_ ¦ '"@ ¦ '#!
¦ 38628 ¦ $~~ ¦ %_~ ¦ %`_ ¦ %a@ ¦ %b! ¦ &@~ ¦ &A_ ¦ &B@ ¦ &C! ¦ '!~ ¦ '"_ ¦ '#@ ¦ '$!
¦ 39496 ¦ %{~ ¦ %|_ ¦ %}@ ¦ %~! ¦ &\~ ¦ &]_ ¦ &^@ ¦ &_! ¦ '=~ ¦ '>_ ¦ '?@ ¦ '@! ¦ (!!
¦ 39527 ¦ %|~ ¦ %}_ ¦ %~@ ¦ &]~ ¦ &^_ ¦ &_@ ¦ &`! ¦ '>~ ¦ '?_ ¦ '@@ ¦ 'A! ¦ (!@ ¦ ("!
¦ 39558 ¦ %}~ ¦ %~_ ¦ &^~ ¦ &__ ¦ &`@ ¦ &a! ¦ '?~ ¦ '@_ ¦ 'A@ ¦ 'B! ¦ (!_ ¦ ("@ ¦ (#!
¦ 39589 ¦ %~~ ¦ &_~ ¦ &`_ ¦ &a@ ¦ &b! ¦ '@~ ¦ 'A_ ¦ 'B@ ¦ 'C! ¦ (!~ ¦ ("_ ¦ (#@ ¦ ($!
¦ 40457 ¦ &{~ ¦ &|_ ¦ &}@ ¦ &~! ¦ '\~ ¦ ']_ ¦ '^@ ¦ '_! ¦ (=~ ¦ (>_ ¦ (?@ ¦ (@! ¦ )!!
¦ 40488 ¦ &|~ ¦ &}_ ¦ &~@ ¦ ']~ ¦ '^_ ¦ '_@ ¦ '`! ¦ (>~ ¦ (?_ ¦ (@@ ¦ (A! ¦ )!@ ¦ )"!
¦ 40519 ¦ &}~ ¦ &~_ ¦ '^~ ¦ '__ ¦ '`@ ¦ 'a! ¦ (?~ ¦ (@_ ¦ (A@ ¦ (B! ¦ )!_ ¦ )"@ ¦ )#!
¦ 40550 ¦ &~~ ¦ '_~ ¦ '`_ ¦ 'a@ ¦ 'b! ¦ (@~ ¦ (A_ ¦ (B@ ¦ (C! ¦ )!~ ¦ )"_ ¦ )#@ ¦ )$!
¦ 41418 ¦ '{~ ¦ '|_ ¦ '}@ ¦ '~! ¦ (\~ ¦ (]_ ¦ (^@ ¦ (_! ¦ )=~ ¦ )>_ ¦ )?@ ¦ )@! ¦ *!!
¦ 41449 ¦ '|~ ¦ '}_ ¦ '~@ ¦ (]~ ¦ (^_ ¦ (_@ ¦ (`! ¦ )>~ ¦ )?_ ¦ )@@ ¦ )A! ¦ *!@ ¦ *"!
¦ 41480 ¦ '}~ ¦ '~_ ¦ (^~ ¦ (__ ¦ (`@ ¦ (a! ¦ )?~ ¦ )@_ ¦ )A@ ¦ )B! ¦ *!_ ¦ *"@ ¦ *#!
¦ 41511 ¦ '~~ ¦ (_~ ¦ (`_ ¦ (a@ ¦ (b! ¦ )@~ ¦ )A_ ¦ )B@ ¦ )C! ¦ *!~ ¦ *"_ ¦ *#@ ¦ *$!
¦ 42379 ¦ ({~ ¦ (|_ ¦ (}@ ¦ (~! ¦ )\~ ¦ )]_ ¦ )^@ ¦ )_! ¦ *=~ ¦ *>_ ¦ *?@ ¦ *@! ¦ +!!
¦ 42410 ¦ (|~ ¦ (}_ ¦ (~@ ¦ )]~ ¦ )^_ ¦ )_@ ¦ )`! ¦ *>~ ¦ *?_ ¦ *@@ ¦ *A! ¦ +!@ ¦ +"!
¦ 42441 ¦ (}~ ¦ (~_ ¦ )^~ ¦ )__ ¦ )`@ ¦ )a! ¦ *?~ ¦ *@_ ¦ *A@ ¦ *B! ¦ +!_ ¦ +"@ ¦ +#!
¦ 42472 ¦ (~~ ¦ )_~ ¦ )`_ ¦ )a@ ¦ )b! ¦ *@~ ¦ *A_ ¦ *B@ ¦ *C! ¦ +!~ ¦ +"_ ¦ +#@ ¦ +$!
¦ 43340 ¦ ){~ ¦ )|_ ¦ )}@ ¦ )~! ¦ *\~ ¦ *]_ ¦ *^@ ¦ *_! ¦ +=~ ¦ +>_ ¦ +?@ ¦ +@! ¦ ,!!
¦ 43371 ¦ )|~ ¦ )}_ ¦ )~@ ¦ *]~ ¦ *^_ ¦ *_@ ¦ *`! ¦ +>~ ¦ +?_ ¦ +@@ ¦ +A! ¦ ,!@ ¦ ,"!
¦ 43402 ¦ )}~ ¦ )~_ ¦ *^~ ¦ *__ ¦ *`@ ¦ *a! ¦ +?~ ¦ +@_ ¦ +A@ ¦ +B! ¦ ,!_ ¦ ,"@ ¦ ,#!
¦ 43433 ¦ )~~ ¦ *_~ ¦ *`_ ¦ *a@ ¦ *b! ¦ +@~ ¦ +A_ ¦ +B@ ¦ +C! ¦ ,!~ ¦ ,"_ ¦ ,#@ ¦ ,$!
¦ 44301 ¦ *{~ ¦ *|_ ¦ *}@ ¦ *~! ¦ +\~ ¦ +]_ ¦ +^@ ¦ +_! ¦ ,=~ ¦ ,>_ ¦ ,?@ ¦ ,@! ¦ -!!
¦ 44332 ¦ *|~ ¦ *}_ ¦ *~@ ¦ +]~ ¦ +^_ ¦ +_@ ¦ +`! ¦ ,>~ ¦ ,?_ ¦ ,@@ ¦ ,A! ¦ -!@ ¦ -"!
¦ 44363 ¦ *}~ ¦ *~_ ¦ +^~ ¦ +__ ¦ +`@ ¦ +a! ¦ ,?~ ¦ ,@_ ¦ ,A@ ¦ ,B! ¦ -!_ ¦ -"@ ¦ -#!
¦ 44394 ¦ *~~ ¦ +_~ ¦ +`_ ¦ +a@ ¦ +b! ¦ ,@~ ¦ ,A_ ¦ ,B@ ¦ ,C! ¦ -!~ ¦ -"_ ¦ -#@ ¦ -$!
¦ 45262 ¦ +{~ ¦ +|_ ¦ +}@ ¦ +~! ¦ ,\~ ¦ ,]_ ¦ ,^@ ¦ ,_! ¦ -=~ ¦ ->_ ¦ -?@ ¦ -@! ¦ .!!
¦ 45293 ¦ +|~ ¦ +}_ ¦ +~@ ¦ ,]~ ¦ ,^_ ¦ ,_@ ¦ ,`! ¦ ->~ ¦ -?_ ¦ -@@ ¦ -A! ¦ .!@ ¦ ."!
¦ 45324 ¦ +}~ ¦ +~_ ¦ ,^~ ¦ ,__ ¦ ,`@ ¦ ,a! ¦ -?~ ¦ -@_ ¦ -A@ ¦ -B! ¦ .!_ ¦ ."@ ¦ .#!
¦ 45355 ¦ +~~ ¦ ,_~ ¦ ,`_ ¦ ,a@ ¦ ,b! ¦ -@~ ¦ -A_ ¦ -B@ ¦ -C! ¦ .!~ ¦ ."_ ¦ .#@ ¦ .$!
¦ 46223 ¦ ,{~ ¦ ,|_ ¦ ,}@ ¦ ,~! ¦ -\~ ¦ -]_ ¦ -^@ ¦ -_! ¦ .=~ ¦ .>_ ¦ .?@ ¦ .@! ¦ /!!
¦ 46254 ¦ ,|~ ¦ ,}_ ¦ ,~@ ¦ -]~ ¦ -^_ ¦ -_@ ¦ -`! ¦ .>~ ¦ .?_ ¦ .@@ ¦ .A! ¦ /!@ ¦ /"!
¦ 46285 ¦ ,}~ ¦ ,~_ ¦ -^~ ¦ -__ ¦ -`@ ¦ -a! ¦ .?~ ¦ .@_ ¦ .A@ ¦ .B! ¦ /!_ ¦ /"@ ¦ /#!
¦ 46316 ¦ ,~~ ¦ -_~ ¦ -`_ ¦ -a@ ¦ -b! ¦ .@~ ¦ .A_ ¦ .B@ ¦ .C! ¦ /!~ ¦ /"_ ¦ /#@ ¦ /$!
¦ 47184 ¦ -{~ ¦ -|_ ¦ -}@ ¦ -~! ¦ .\~ ¦ .]_ ¦ .^@ ¦ ._! ¦ /=~ ¦ />_ ¦ /?@ ¦ /@! ¦ 0!!
¦ 47215 ¦ -|~ ¦ -}_ ¦ -~@ ¦ .]~ ¦ .^_ ¦ ._@ ¦ .`! ¦ />~ ¦ /?_ ¦ /@@ ¦ /A! ¦ 0!@ ¦ 0"!
¦ 47246 ¦ -}~ ¦ -~_ ¦ .^~ ¦ .__ ¦ .`@ ¦ .a! ¦ /?~ ¦ /@_ ¦ /A@ ¦ /B! ¦ 0!_ ¦ 0"@ ¦ 0#!
¦ 47277 ¦ -~~ ¦ ._~ ¦ .`_ ¦ .a@ ¦ .b! ¦ /@~ ¦ /A_ ¦ /B@ ¦ /C! ¦ 0!~ ¦ 0"_ ¦ 0#@ ¦ 0$!
¦ 48145 ¦ .{~ ¦ .|_ ¦ .}@ ¦ .~! ¦ /\~ ¦ /]_ ¦ /^@ ¦ /_! ¦ 0=~ ¦ 0>_ ¦ 0?@ ¦ 0@! ¦ 1!!
¦ 48176 ¦ .|~ ¦ .}_ ¦ .~@ ¦ /]~ ¦ /^_ ¦ /_@ ¦ /`! ¦ 0>~ ¦ 0?_ ¦ 0@@ ¦ 0A! ¦ 1!@ ¦ 1"!
¦ 48207 ¦ .}~ ¦ .~_ ¦ /^~ ¦ /__ ¦ /`@ ¦ /a! ¦ 0?~ ¦ 0@_ ¦ 0A@ ¦ 0B! ¦ 1!_ ¦ 1"@ ¦ 1#!
¦ 48238 ¦ .~~ ¦ /_~ ¦ /`_ ¦ /a@ ¦ /b! ¦ 0@~ ¦ 0A_ ¦ 0B@ ¦ 0C! ¦ 1!~ ¦ 1"_ ¦ 1#@ ¦ 1$!
¦ 49106 ¦ /{~ ¦ /|_ ¦ /}@ ¦ /~! ¦ 0\~ ¦ 0]_ ¦ 0^@ ¦ 0_! ¦ 1=~ ¦ 1>_ ¦ 1?@ ¦ 1@! ¦ 2!!
¦ 49137 ¦ /|~ ¦ /}_ ¦ /~@ ¦ 0]~ ¦ 0^_ ¦ 0_@ ¦ 0`! ¦ 1>~ ¦ 1?_ ¦ 1@@ ¦ 1A! ¦ 2!@ ¦ 2"!
¦ 49168 ¦ /}~ ¦ /~_ ¦ 0^~ ¦ 0__ ¦ 0`@ ¦ 0a! ¦ 1?~ ¦ 1@_ ¦ 1A@ ¦ 1B! ¦ 2!_ ¦ 2"@ ¦ 2#!
¦ 49199 ¦ /~~ ¦ 0_~ ¦ 0`_ ¦ 0a@ ¦ 0b! ¦ 1@~ ¦ 1A_ ¦ 1B@ ¦ 1C! ¦ 2!~ ¦ 2"_ ¦ 2#@ ¦ 2$!
¦ 50067 ¦ 0{~ ¦ 0|_ ¦ 0}@ ¦ 0~! ¦ 1\~ ¦ 1]_ ¦ 1^@ ¦ 1_! ¦ 2=~ ¦ 2>_ ¦ 2?@ ¦ 2@! ¦ 3!!
¦ 50098 ¦ 0|~ ¦ 0}_ ¦ 0~@ ¦ 1]~ ¦ 1^_ ¦ 1_@ ¦ 1`! ¦ 2>~ ¦ 2?_ ¦ 2@@ ¦ 2A! ¦ 3!@ ¦ 3"!
¦ 50129 ¦ 0}~ ¦ 0~_ ¦ 1^~ ¦ 1__ ¦ 1`@ ¦ 1a! ¦ 2?~ ¦ 2@_ ¦ 2A@ ¦ 2B! ¦ 3!_ ¦ 3"@ ¦ 3#!
¦ 50160 ¦ 0~~ ¦ 1_~ ¦ 1`_ ¦ 1a@ ¦ 1b! ¦ 2@~ ¦ 2A_ ¦ 2B@ ¦ 2C! ¦ 3!~ ¦ 3"_ ¦ 3#@ ¦ 3$!
¦ 51028 ¦ 1{~ ¦ 1|_ ¦ 1}@ ¦ 1~! ¦ 2\~ ¦ 2]_ ¦ 2^@ ¦ 2_! ¦ 3=~ ¦ 3>_ ¦ 3?@ ¦ 3@! ¦ 4!!
¦ 51059 ¦ 1|~ ¦ 1}_ ¦ 1~@ ¦ 2]~ ¦ 2^_ ¦ 2_@ ¦ 2`! ¦ 3>~ ¦ 3?_ ¦ 3@@ ¦ 3A! ¦ 4!@ ¦ 4"!
¦ 51090 ¦ 1}~ ¦ 1~_ ¦ 2^~ ¦ 2__ ¦ 2`@ ¦ 2a! ¦ 3?~ ¦ 3@_ ¦ 3A@ ¦ 3B! ¦ 4!_ ¦ 4"@ ¦ 4#!
¦ 51121 ¦ 1~~ ¦ 2_~ ¦ 2`_ ¦ 2a@ ¦ 2b! ¦ 3@~ ¦ 3A_ ¦ 3B@ ¦ 3C! ¦ 4!~ ¦ 4"_ ¦ 4#@ ¦ 4$!
¦ 51989 ¦ 2{~ ¦ 2|_ ¦ 2}@ ¦ 2~! ¦ 3\~ ¦ 3]_ ¦ 3^@ ¦ 3_! ¦ 4=~ ¦ 4>_ ¦ 4?@ ¦ 4@! ¦ 5!!
¦ 52020 ¦ 2|~ ¦ 2}_ ¦ 2~@ ¦ 3]~ ¦ 3^_ ¦ 3_@ ¦ 3`! ¦ 4>~ ¦ 4?_ ¦ 4@@ ¦ 4A! ¦ 5!@ ¦ 5"!
¦ 52051 ¦ 2}~ ¦ 2~_ ¦ 3^~ ¦ 3__ ¦ 3`@ ¦ 3a! ¦ 4?~ ¦ 4@_ ¦ 4A@ ¦ 4B! ¦ 5!_ ¦ 5"@ ¦ 5#!
¦ 52082 ¦ 2~~ ¦ 3_~ ¦ 3`_ ¦ 3a@ ¦ 3b! ¦ 4@~ ¦ 4A_ ¦ 4B@ ¦ 4C! ¦ 5!~ ¦ 5"_ ¦ 5#@ ¦ 5$!
¦ 52950 ¦ 3{~ ¦ 3|_ ¦ 3}@ ¦ 3~! ¦ 4\~ ¦ 4]_ ¦ 4^@ ¦ 4_! ¦ 5=~ ¦ 5>_ ¦ 5?@ ¦ 5@! ¦ 6!!
¦ 52981 ¦ 3|~ ¦ 3}_ ¦ 3~@ ¦ 4]~ ¦ 4^_ ¦ 4_@ ¦ 4`! ¦ 5>~ ¦ 5?_ ¦ 5@@ ¦ 5A! ¦ 6!@ ¦ 6"!
¦ 53012 ¦ 3}~ ¦ 3~_ ¦ 4^~ ¦ 4__ ¦ 4`@ ¦ 4a! ¦ 5?~ ¦ 5@_ ¦ 5A@ ¦ 5B! ¦ 6!_ ¦ 6"@ ¦ 6#!
¦ 53043 ¦ 3~~ ¦ 4_~ ¦ 4`_ ¦ 4a@ ¦ 4b! ¦ 5@~ ¦ 5A_ ¦ 5B@ ¦ 5C! ¦ 6!~ ¦ 6"_ ¦ 6#@ ¦ 6$!
¦ 53911 ¦ 4{~ ¦ 4|_ ¦ 4}@ ¦ 4~! ¦ 5\~ ¦ 5]_ ¦ 5^@ ¦ 5_! ¦ 6=~ ¦ 6>_ ¦ 6?@ ¦ 6@! ¦ 7!!
¦ 53942 ¦ 4|~ ¦ 4}_ ¦ 4~@ ¦ 5]~ ¦ 5^_ ¦ 5_@ ¦ 5`! ¦ 6>~ ¦ 6?_ ¦ 6@@ ¦ 6A! ¦ 7!@ ¦ 7"!
¦ 53973 ¦ 4}~ ¦ 4~_ ¦ 5^~ ¦ 5__ ¦ 5`@ ¦ 5a! ¦ 6?~ ¦ 6@_ ¦ 6A@ ¦ 6B! ¦ 7!_ ¦ 7"@ ¦ 7#!
¦ 54004 ¦ 4~~ ¦ 5_~ ¦ 5`_ ¦ 5a@ ¦ 5b! ¦ 6@~ ¦ 6A_ ¦ 6B@ ¦ 6C! ¦ 7!~ ¦ 7"_ ¦ 7#@ ¦ 7$!
¦ 54872 ¦ 5{~ ¦ 5|_ ¦ 5}@ ¦ 5~! ¦ 6\~ ¦ 6]_ ¦ 6^@ ¦ 6_! ¦ 7=~ ¦ 7>_ ¦ 7?@ ¦ 7@! ¦ 8!!
¦ 54903 ¦ 5|~ ¦ 5}_ ¦ 5~@ ¦ 6]~ ¦ 6^_ ¦ 6_@ ¦ 6`! ¦ 7>~ ¦ 7?_ ¦ 7@@ ¦ 7A! ¦ 8!@ ¦ 8"!
¦ 54934 ¦ 5}~ ¦ 5~_ ¦ 6^~ ¦ 6__ ¦ 6`@ ¦ 6a! ¦ 7?~ ¦ 7@_ ¦ 7A@ ¦ 7B! ¦ 8!_ ¦ 8"@ ¦ 8#!
¦ 54965 ¦ 5~~ ¦ 6_~ ¦ 6`_ ¦ 6a@ ¦ 6b! ¦ 7@~ ¦ 7A_ ¦ 7B@ ¦ 7C! ¦ 8!~ ¦ 8"_ ¦ 8#@ ¦ 8$!
¦ 55833 ¦ 6{~ ¦ 6|_ ¦ 6}@ ¦ 6~! ¦ 7\~ ¦ 7]_ ¦ 7^@ ¦ 7_! ¦ 8=~ ¦ 8>_ ¦ 8?@ ¦ 8@! ¦ 9!!
¦ 55864 ¦ 6|~ ¦ 6}_ ¦ 6~@ ¦ 7]~ ¦ 7^_ ¦ 7_@ ¦ 7`! ¦ 8>~ ¦ 8?_ ¦ 8@@ ¦ 8A! ¦ 9!@ ¦ 9"!
¦ 55895 ¦ 6}~ ¦ 6~_ ¦ 7^~ ¦ 7__ ¦ 7`@ ¦ 7a! ¦ 8?~ ¦ 8@_ ¦ 8A@ ¦ 8B! ¦ 9!_ ¦ 9"@ ¦ 9#!
¦ 55926 ¦ 6~~ ¦ 7_~ ¦ 7`_ ¦ 7a@ ¦ 7b! ¦ 8@~ ¦ 8A_ ¦ 8B@ ¦ 8C! ¦ 9!~ ¦ 9"_ ¦ 9#@ ¦ 9$!
¦ 56794 ¦ 7{~ ¦ 7|_ ¦ 7}@ ¦ 7~! ¦ 8\~ ¦ 8]_ ¦ 8^@ ¦ 8_! ¦ 9=~ ¦ 9>_ ¦ 9?@ ¦ 9@! ¦ :!!
¦ 56825 ¦ 7|~ ¦ 7}_ ¦ 7~@ ¦ 8]~ ¦ 8^_ ¦ 8_@ ¦ 8`! ¦ 9>~ ¦ 9?_ ¦ 9@@ ¦ 9A! ¦ :!@ ¦ :"!
¦ 56856 ¦ 7}~ ¦ 7~_ ¦ 8^~ ¦ 8__ ¦ 8`@ ¦ 8a! ¦ 9?~ ¦ 9@_ ¦ 9A@ ¦ 9B! ¦ :!_ ¦ :"@ ¦ :#!
¦ 56887 ¦ 7~~ ¦ 8_~ ¦ 8`_ ¦ 8a@ ¦ 8b! ¦ 9@~ ¦ 9A_ ¦ 9B@ ¦ 9C! ¦ :!~ ¦ :"_ ¦ :#@ ¦ :$!
¦ 57755 ¦ 8{~ ¦ 8|_ ¦ 8}@ ¦ 8~! ¦ 9\~ ¦ 9]_ ¦ 9^@ ¦ 9_! ¦ :=~ ¦ :>_ ¦ :?@ ¦ :@! ¦ ;!!
¦ 57786 ¦ 8|~ ¦ 8}_ ¦ 8~@ ¦ 9]~ ¦ 9^_ ¦ 9_@ ¦ 9`! ¦ :>~ ¦ :?_ ¦ :@@ ¦ :A! ¦ ;!@ ¦ ;"!
¦ 57817 ¦ 8}~ ¦ 8~_ ¦ 9^~ ¦ 9__ ¦ 9`@ ¦ 9a! ¦ :?~ ¦ :@_ ¦ :A@ ¦ :B! ¦ ;!_ ¦ ;"@ ¦ ;#!
¦ 57848 ¦ 8~~ ¦ 9_~ ¦ 9`_ ¦ 9a@ ¦ 9b! ¦ :@~ ¦ :A_ ¦ :B@ ¦ :C! ¦ ;!~ ¦ ;"_ ¦ ;#@ ¦ ;$!
¦ 58716 ¦ 9{~ ¦ 9|_ ¦ 9}@ ¦ 9~! ¦ :\~ ¦ :]_ ¦ :^@ ¦ :_! ¦ ;=~ ¦ ;>_ ¦ ;?@ ¦ ;@! ¦ <!!
¦ 58747 ¦ 9|~ ¦ 9}_ ¦ 9~@ ¦ :]~ ¦ :^_ ¦ :_@ ¦ :`! ¦ ;>~ ¦ ;?_ ¦ ;@@ ¦ ;A! ¦ <!@ ¦ <"!
¦ 58778 ¦ 9}~ ¦ 9~_ ¦ :^~ ¦ :__ ¦ :`@ ¦ :a! ¦ ;?~ ¦ ;@_ ¦ ;A@ ¦ ;B! ¦ <!_ ¦ <"@ ¦ <#!
¦ 58809 ¦ 9~~ ¦ :_~ ¦ :`_ ¦ :a@ ¦ :b! ¦ ;@~ ¦ ;A_ ¦ ;B@ ¦ ;C! ¦ <!~ ¦ <"_ ¦ <#@ ¦ <$!
¦ 59677 ¦ :{~ ¦ :|_ ¦ :}@ ¦ :~! ¦ ;\~ ¦ ;]_ ¦ ;^@ ¦ ;_! ¦ <=~ ¦ <>_ ¦ <?@ ¦ <@! ¦ =!!
¦ 59708 ¦ :|~ ¦ :}_ ¦ :~@ ¦ ;]~ ¦ ;^_ ¦ ;_@ ¦ ;`! ¦ <>~ ¦ <?_ ¦ <@@ ¦ <A! ¦ =!@ ¦ ="!
¦ 59739 ¦ :}~ ¦ :~_ ¦ ;^~ ¦ ;__ ¦ ;`@ ¦ ;a! ¦ <?~ ¦ <@_ ¦ <A@ ¦ <B! ¦ =!_ ¦ ="@ ¦ =#!
¦ 59770 ¦ :~~ ¦ ;_~ ¦ ;`_ ¦ ;a@ ¦ ;b! ¦ <@~ ¦ <A_ ¦ <B@ ¦ <C! ¦ =!~ ¦ ="_ ¦ =#@ ¦ =$!
¦ 60638 ¦ ;{~ ¦ ;|_ ¦ ;}@ ¦ ;~! ¦ <\~ ¦ <]_ ¦ <^@ ¦ <_! ¦ ==~ ¦ =>_ ¦ =?@ ¦ =@! ¦ >!!
¦ 60669 ¦ ;|~ ¦ ;}_ ¦ ;~@ ¦ <]~ ¦ <^_ ¦ <_@ ¦ <`! ¦ =>~ ¦ =?_ ¦ =@@ ¦ =A! ¦ >!@ ¦ >"!
¦ 60700 ¦ ;}~ ¦ ;~_ ¦ <^~ ¦ <__ ¦ <`@ ¦ <a! ¦ =?~ ¦ =@_ ¦ =A@ ¦ =B! ¦ >!_ ¦ >"@ ¦ >#!
¦ 60731 ¦ ;~~ ¦ <_~ ¦ <`_ ¦ <a@ ¦ <b! ¦ =@~ ¦ =A_ ¦ =B@ ¦ =C! ¦ >!~ ¦ >"_ ¦ >#@ ¦ >$!
¦ 61599 ¦ <{~ ¦ <|_ ¦ <}@ ¦ <~! ¦ =\~ ¦ =]_ ¦ =^@ ¦ =_! ¦ >=~ ¦ >>_ ¦ >?@ ¦ >@! ¦ ?!!
¦ 61630 ¦ <|~ ¦ <}_ ¦ <~@ ¦ =]~ ¦ =^_ ¦ =_@ ¦ =`! ¦ >>~ ¦ >?_ ¦ >@@ ¦ >A! ¦ ?!@ ¦ ?"!
¦ 61661 ¦ <}~ ¦ <~_ ¦ =^~ ¦ =__ ¦ =`@ ¦ =a! ¦ >?~ ¦ >@_ ¦ >A@ ¦ >B! ¦ ?!_ ¦ ?"@ ¦ ?#!
¦ 61692 ¦ <~~ ¦ =_~ ¦ =`_ ¦ =a@ ¦ =b! ¦ >@~ ¦ >A_ ¦ >B@ ¦ >C! ¦ ?!~ ¦ ?"_ ¦ ?#@ ¦ ?$!
¦ 62560 ¦ ={~ ¦ =|_ ¦ =}@ ¦ =~! ¦ >\~ ¦ >]_ ¦ >^@ ¦ >_! ¦ ?=~ ¦ ?>_ ¦ ??@ ¦ ?@! ¦ @!!
¦ 62591 ¦ =|~ ¦ =}_ ¦ =~@ ¦ >]~ ¦ >^_ ¦ >_@ ¦ >`! ¦ ?>~ ¦ ??_ ¦ ?@@ ¦ ?A! ¦ @!@ ¦ @"!
¦ 62622 ¦ =}~ ¦ =~_ ¦ >^~ ¦ >__ ¦ >`@ ¦ >a! ¦ ??~ ¦ ?@_ ¦ ?A@ ¦ ?B! ¦ @!_ ¦ @"@ ¦ @#!
¦ 62653 ¦ =~~ ¦ >_~ ¦ >`_ ¦ >a@ ¦ >b! ¦ ?@~ ¦ ?A_ ¦ ?B@ ¦ ?C! ¦ @!~ ¦ @"_ ¦ @#@ ¦ @$!
¦ 63521 ¦ >{~ ¦ >|_ ¦ >}@ ¦ >~! ¦ ?\~ ¦ ?]_ ¦ ?^@ ¦ ?_! ¦ @=~ ¦ @>_ ¦ @?@ ¦ @@! ¦ A!!
¦ 63552 ¦ >|~ ¦ >}_ ¦ >~@ ¦ ?]~ ¦ ?^_ ¦ ?_@ ¦ ?`! ¦ @>~ ¦ @?_ ¦ @@@ ¦ @A! ¦ A!@ ¦ A"!
¦ 63583 ¦ >}~ ¦ >~_ ¦ ?^~ ¦ ?__ ¦ ?`@ ¦ ?a! ¦ @?~ ¦ @@_ ¦ @A@ ¦ @B! ¦ A!_ ¦ A"@ ¦ A#!
¦ 63614 ¦ >~~ ¦ ?_~ ¦ ?`_ ¦ ?a@ ¦ ?b! ¦ @@~ ¦ @A_ ¦ @B@ ¦ @C! ¦ A!~ ¦ A"_ ¦ A#@ ¦ A$!
¦ 64482 ¦ ?{~ ¦ ?|_ ¦ ?}@ ¦ ?~! ¦ @\~ ¦ @]_ ¦ @^@ ¦ @_! ¦ A=~ ¦ A>_ ¦ A?@ ¦ A@! ¦ B!!
¦ 64513 ¦ ?|~ ¦ ?}_ ¦ ?~@ ¦ @]~ ¦ @^_ ¦ @_@ ¦ @`! ¦ A>~ ¦ A?_ ¦ A@@ ¦ AA! ¦ B!@ ¦ B"!
¦ 64544 ¦ ?}~ ¦ ?~_ ¦ @^~ ¦ @__ ¦ @`@ ¦ @a! ¦ A?~ ¦ A@_ ¦ AA@ ¦ AB! ¦ B!_ ¦ B"@ ¦ B#!
¦ 64575 ¦ ?~~ ¦ @_~ ¦ @`_ ¦ @a@ ¦ @b! ¦ A@~ ¦ AA_ ¦ AB@ ¦ AC! ¦ B!~ ¦ B"_ ¦ B#@ ¦ B$!
¦ 65443 ¦ @{~ ¦ @|_ ¦ @}@ ¦ @~! ¦ A\~ ¦ A]_ ¦ A^@ ¦ A_! ¦ B=~ ¦ B>_ ¦ B?@ ¦ B@! ¦ C!!
¦ 65474 ¦ @|~ ¦ @}_ ¦ @~@ ¦ A]~ ¦ A^_ ¦ A_@ ¦ A`! ¦ B>~ ¦ B?_ ¦ B@@ ¦ BA! ¦ C!@ ¦ C"!
¦ 65505 ¦ @}~ ¦ @~_ ¦ A^~ ¦ A__ ¦ A`@ ¦ Aa! ¦ B?~ ¦ B@_ ¦ BA@ ¦ BB! ¦ C!_ ¦ C"@ ¦ C#!
¦ 65536 ¦ @~~ ¦ A_~ ¦ A`_ ¦ Aa@ ¦ Ab! ¦ B@~ ¦ BA_ ¦ BB@ ¦ BC! ¦ C!~ ¦ C"_ ¦ C#@ ¦ C$!
¦ 66404 ¦ A{~ ¦ A|_ ¦ A}@ ¦ A~! ¦ B\~ ¦ B]_ ¦ B^@ ¦ B_! ¦ C=~ ¦ C>_ ¦ C?@ ¦ C@! ¦ D!!
¦ 66435 ¦ A|~ ¦ A}_ ¦ A~@ ¦ B]~ ¦ B^_ ¦ B_@ ¦ B`! ¦ C>~ ¦ C?_ ¦ C@@ ¦ CA! ¦ D!@ ¦ D"!
¦ 66466 ¦ A}~ ¦ A~_ ¦ B^~ ¦ B__ ¦ B`@ ¦ Ba! ¦ C?~ ¦ C@_ ¦ CA@ ¦ CB! ¦ D!_ ¦ D"@ ¦ D#!
¦ 66497 ¦ A~~ ¦ B_~ ¦ B`_ ¦ Ba@ ¦ Bb! ¦ C@~ ¦ CA_ ¦ CB@ ¦ CC! ¦ D!~ ¦ D"_ ¦ D#@ ¦ D$!
¦ 67365 ¦ B{~ ¦ B|_ ¦ B}@ ¦ B~! ¦ C\~ ¦ C]_ ¦ C^@ ¦ C_! ¦ D=~ ¦ D>_ ¦ D?@ ¦ D@! ¦ E!!
¦ 67396 ¦ B|~ ¦ B}_ ¦ B~@ ¦ C]~ ¦ C^_ ¦ C_@ ¦ C`! ¦ D>~ ¦ D?_ ¦ D@@ ¦ DA! ¦ E!@ ¦ E"!
¦ 67427 ¦ B}~ ¦ B~_ ¦ C^~ ¦ C__ ¦ C`@ ¦ Ca! ¦ D?~ ¦ D@_ ¦ DA@ ¦ DB! ¦ E!_ ¦ E"@ ¦ E#!
¦ 67458 ¦ B~~ ¦ C_~ ¦ C`_ ¦ Ca@ ¦ Cb! ¦ D@~ ¦ DA_ ¦ DB@ ¦ DC! ¦ E!~ ¦ E"_ ¦ E#@ ¦ E$!
¦ 68326 ¦ C{~ ¦ C|_ ¦ C}@ ¦ C~! ¦ D\~ ¦ D]_ ¦ D^@ ¦ D_! ¦ E=~ ¦ E>_ ¦ E?@ ¦ E@! ¦ F!!
¦ 68357 ¦ C|~ ¦ C}_ ¦ C~@ ¦ D]~ ¦ D^_ ¦ D_@ ¦ D`! ¦ E>~ ¦ E?_ ¦ E@@ ¦ EA! ¦ F!@ ¦ F"!
¦ 68388 ¦ C}~ ¦ C~_ ¦ D^~ ¦ D__ ¦ D`@ ¦ Da! ¦ E?~ ¦ E@_ ¦ EA@ ¦ EB! ¦ F!_ ¦ F"@ ¦ F#!
¦ 68419 ¦ C~~ ¦ D_~ ¦ D`_ ¦ Da@ ¦ Db! ¦ E@~ ¦ EA_ ¦ EB@ ¦ EC! ¦ F!~ ¦ F"_ ¦ F#@ ¦ F$!
¦ 69287 ¦ D{~ ¦ D|_ ¦ D}@ ¦ D~! ¦ E\~ ¦ E]_ ¦ E^@ ¦ E_! ¦ F=~ ¦ F>_ ¦ F?@ ¦ F@! ¦ G!!
¦ 69318 ¦ D|~ ¦ D}_ ¦ D~@ ¦ E]~ ¦ E^_ ¦ E_@ ¦ E`! ¦ F>~ ¦ F?_ ¦ F@@ ¦ FA! ¦ G!@ ¦ G"!
¦ 69349 ¦ D}~ ¦ D~_ ¦ E^~ ¦ E__ ¦ E`@ ¦ Ea! ¦ F?~ ¦ F@_ ¦ FA@ ¦ FB! ¦ G!_ ¦ G"@ ¦ G#!
¦ 69380 ¦ D~~ ¦ E_~ ¦ E`_ ¦ Ea@ ¦ Eb! ¦ F@~ ¦ FA_ ¦ FB@ ¦ FC! ¦ G!~ ¦ G"_ ¦ G#@ ¦ G$!
¦ 70248 ¦ E{~ ¦ E|_ ¦ E}@ ¦ E~! ¦ F\~ ¦ F]_ ¦ F^@ ¦ F_! ¦ G=~ ¦ G>_ ¦ G?@ ¦ G@! ¦ H!!
¦ 70279 ¦ E|~ ¦ E}_ ¦ E~@ ¦ F]~ ¦ F^_ ¦ F_@ ¦ F`! ¦ G>~ ¦ G?_ ¦ G@@ ¦ GA! ¦ H!@ ¦ H"!
¦ 70310 ¦ E}~ ¦ E~_ ¦ F^~ ¦ F__ ¦ F`@ ¦ Fa! ¦ G?~ ¦ G@_ ¦ GA@ ¦ GB! ¦ H!_ ¦ H"@ ¦ H#!
¦ 70341 ¦ E~~ ¦ F_~ ¦ F`_ ¦ Fa@ ¦ Fb! ¦ G@~ ¦ GA_ ¦ GB@ ¦ GC! ¦ H!~ ¦ H"_ ¦ H#@ ¦ H$!
¦ 71209 ¦ F{~ ¦ F|_ ¦ F}@ ¦ F~! ¦ G\~ ¦ G]_ ¦ G^@ ¦ G_! ¦ H=~ ¦ H>_ ¦ H?@ ¦ H@! ¦ I!!
¦ 71240 ¦ F|~ ¦ F}_ ¦ F~@ ¦ G]~ ¦ G^_ ¦ G_@ ¦ G`! ¦ H>~ ¦ H?_ ¦ H@@ ¦ HA! ¦ I!@ ¦ I"!
¦ 71271 ¦ F}~ ¦ F~_ ¦ G^~ ¦ G__ ¦ G`@ ¦ Ga! ¦ H?~ ¦ H@_ ¦ HA@ ¦ HB! ¦ I!_ ¦ I"@ ¦ I#!
¦ 71302 ¦ F~~ ¦ G_~ ¦ G`_ ¦ Ga@ ¦ Gb! ¦ H@~ ¦ HA_ ¦ HB@ ¦ HC! ¦ I!~ ¦ I"_ ¦ I#@ ¦ I$!
¦ 72170 ¦ G{~ ¦ G|_ ¦ G}@ ¦ G~! ¦ H\~ ¦ H]_ ¦ H^@ ¦ H_! ¦ I=~ ¦ I>_ ¦ I?@ ¦ I@! ¦ J!!
¦ 72201 ¦ G|~ ¦ G}_ ¦ G~@ ¦ H]~ ¦ H^_ ¦ H_@ ¦ H`! ¦ I>~ ¦ I?_ ¦ I@@ ¦ IA! ¦ J!@ ¦ J"!
¦ 72232 ¦ G}~ ¦ G~_ ¦ H^~ ¦ H__ ¦ H`@ ¦ Ha! ¦ I?~ ¦ I@_ ¦ IA@ ¦ IB! ¦ J!_ ¦ J"@ ¦ J#!
¦ 72263 ¦ G~~ ¦ H_~ ¦ H`_ ¦ Ha@ ¦ Hb! ¦ I@~ ¦ IA_ ¦ IB@ ¦ IC! ¦ J!~ ¦ J"_ ¦ J#@ ¦ J$!
¦ 73131 ¦ H{~ ¦ H|_ ¦ H}@ ¦ H~! ¦ I\~ ¦ I]_ ¦ I^@ ¦ I_! ¦ J=~ ¦ J>_ ¦ J?@ ¦ J@! ¦ K!!
¦ 73162 ¦ H|~ ¦ H}_ ¦ H~@ ¦ I]~ ¦ I^_ ¦ I_@ ¦ I`! ¦ J>~ ¦ J?_ ¦ J@@ ¦ JA! ¦ K!@ ¦ K"!
¦ 73193 ¦ H}~ ¦ H~_ ¦ I^~ ¦ I__ ¦ I`@ ¦ Ia! ¦ J?~ ¦ J@_ ¦ JA@ ¦ JB! ¦ K!_ ¦ K"@ ¦ K#!
¦ 73224 ¦ H~~ ¦ I_~ ¦ I`_ ¦ Ia@ ¦ Ib! ¦ J@~ ¦ JA_ ¦ JB@ ¦ JC! ¦ K!~ ¦ K"_ ¦ K#@ ¦ K$!
¦ 74092 ¦ I{~ ¦ I|_ ¦ I}@ ¦ I~! ¦ J\~ ¦ J]_ ¦ J^@ ¦ J_! ¦ K=~ ¦ K>_ ¦ K?@ ¦ K@! ¦ L!!
¦ 74123 ¦ I|~ ¦ I}_ ¦ I~@ ¦ J]~ ¦ J^_ ¦ J_@ ¦ J`! ¦ K>~ ¦ K?_ ¦ K@@ ¦ KA! ¦ L!@ ¦ L"!
¦ 74154 ¦ I}~ ¦ I~_ ¦ J^~ ¦ J__ ¦ J`@ ¦ Ja! ¦ K?~ ¦ K@_ ¦ KA@ ¦ KB! ¦ L!_ ¦ L"@ ¦ L#!
¦ 74185 ¦ I~~ ¦ J_~ ¦ J`_ ¦ Ja@ ¦ Jb! ¦ K@~ ¦ KA_ ¦ KB@ ¦ KC! ¦ L!~ ¦ L"_ ¦ L#@ ¦ L$!
¦ 75053 ¦ J{~ ¦ J|_ ¦ J}@ ¦ J~! ¦ K\~ ¦ K]_ ¦ K^@ ¦ K_! ¦ L=~ ¦ L>_ ¦ L?@ ¦ L@! ¦ M!!
¦ 75084 ¦ J|~ ¦ J}_ ¦ J~@ ¦ K]~ ¦ K^_ ¦ K_@ ¦ K`! ¦ L>~ ¦ L?_ ¦ L@@ ¦ LA! ¦ M!@ ¦ M"!
¦ 75115 ¦ J}~ ¦ J~_ ¦ K^~ ¦ K__ ¦ K`@ ¦ Ka! ¦ L?~ ¦ L@_ ¦ LA@ ¦ LB! ¦ M!_ ¦ M"@ ¦ M#!
¦ 75146 ¦ J~~ ¦ K_~ ¦ K`_ ¦ Ka@ ¦ Kb! ¦ L@~ ¦ LA_ ¦ LB@ ¦ LC! ¦ M!~ ¦ M"_ ¦ M#@ ¦ M$!
¦ 76014 ¦ K{~ ¦ K|_ ¦ K}@ ¦ K~! ¦ L\~ ¦ L]_ ¦ L^@ ¦ L_! ¦ M=~ ¦ M>_ ¦ M?@ ¦ M@! ¦ N!!
¦ 76045 ¦ K|~ ¦ K}_ ¦ K~@ ¦ L]~ ¦ L^_ ¦ L_@ ¦ L`! ¦ M>~ ¦ M?_ ¦ M@@ ¦ MA! ¦ N!@ ¦ N"!
¦ 76076 ¦ K}~ ¦ K~_ ¦ L^~ ¦ L__ ¦ L`@ ¦ La! ¦ M?~ ¦ M@_ ¦ MA@ ¦ MB! ¦ N!_ ¦ N"@ ¦ N#!
¦ 76107 ¦ K~~ ¦ L_~ ¦ L`_ ¦ La@ ¦ Lb! ¦ M@~ ¦ MA_ ¦ MB@ ¦ MC! ¦ N!~ ¦ N"_ ¦ N#@ ¦ N$!
¦ 76975 ¦ L{~ ¦ L|_ ¦ L}@ ¦ L~! ¦ M\~ ¦ M]_ ¦ M^@ ¦ M_! ¦ N=~ ¦ N>_ ¦ N?@ ¦ N@! ¦ O!!
¦ 77006 ¦ L|~ ¦ L}_ ¦ L~@ ¦ M]~ ¦ M^_ ¦ M_@ ¦ M`! ¦ N>~ ¦ N?_ ¦ N@@ ¦ NA! ¦ O!@ ¦ O"!
¦ 77037 ¦ L}~ ¦ L~_ ¦ M^~ ¦ M__ ¦ M`@ ¦ Ma! ¦ N?~ ¦ N@_ ¦ NA@ ¦ NB! ¦ O!_ ¦ O"@ ¦ O#!
¦ 77068 ¦ L~~ ¦ M_~ ¦ M`_ ¦ Ma@ ¦ Mb! ¦ N@~ ¦ NA_ ¦ NB@ ¦ NC! ¦ O!~ ¦ O"_ ¦ O#@ ¦ O$!
¦ 77936 ¦ M{~ ¦ M|_ ¦ M}@ ¦ M~! ¦ N\~ ¦ N]_ ¦ N^@ ¦ N_! ¦ O=~ ¦ O>_ ¦ O?@ ¦ O@! ¦ P!!
¦ 77967 ¦ M|~ ¦ M}_ ¦ M~@ ¦ N]~ ¦ N^_ ¦ N_@ ¦ N`! ¦ O>~ ¦ O?_ ¦ O@@ ¦ OA! ¦ P!@ ¦ P"!
¦ 77998 ¦ M}~ ¦ M~_ ¦ N^~ ¦ N__ ¦ N`@ ¦ Na! ¦ O?~ ¦ O@_ ¦ OA@ ¦ OB! ¦ P!_ ¦ P"@ ¦ P#!
¦ 78029 ¦ M~~ ¦ N_~ ¦ N`_ ¦ Na@ ¦ Nb! ¦ O@~ ¦ OA_ ¦ OB@ ¦ OC! ¦ P!~ ¦ P"_ ¦ P#@ ¦ P$!
¦ 78897 ¦ N{~ ¦ N|_ ¦ N}@ ¦ N~! ¦ O\~ ¦ O]_ ¦ O^@ ¦ O_! ¦ P=~ ¦ P>_ ¦ P?@ ¦ P@! ¦ Q!!
¦ 78928 ¦ N|~ ¦ N}_ ¦ N~@ ¦ O]~ ¦ O^_ ¦ O_@ ¦ O`! ¦ P>~ ¦ P?_ ¦ P@@ ¦ PA! ¦ Q!@ ¦ Q"!
¦ 78959 ¦ N}~ ¦ N~_ ¦ O^~ ¦ O__ ¦ O`@ ¦ Oa! ¦ P?~ ¦ P@_ ¦ PA@ ¦ PB! ¦ Q!_ ¦ Q"@ ¦ Q#!
¦ 78990 ¦ N~~ ¦ O_~ ¦ O`_ ¦ Oa@ ¦ Ob! ¦ P@~ ¦ PA_ ¦ PB@ ¦ PC! ¦ Q!~ ¦ Q"_ ¦ Q#@ ¦ Q$!
¦ 79858 ¦ O{~ ¦ O|_ ¦ O}@ ¦ O~! ¦ P\~ ¦ P]_ ¦ P^@ ¦ P_! ¦ Q=~ ¦ Q>_ ¦ Q?@ ¦ Q@! ¦ R!!
¦ 79889 ¦ O|~ ¦ O}_ ¦ O~@ ¦ P]~ ¦ P^_ ¦ P_@ ¦ P`! ¦ Q>~ ¦ Q?_ ¦ Q@@ ¦ QA! ¦ R!@ ¦ R"!
¦ 79920 ¦ O}~ ¦ O~_ ¦ P^~ ¦ P__ ¦ P`@ ¦ Pa! ¦ Q?~ ¦ Q@_ ¦ QA@ ¦ QB! ¦ R!_ ¦ R"@ ¦ R#!
¦ 79951 ¦ O~~ ¦ P_~ ¦ P`_ ¦ Pa@ ¦ Pb! ¦ Q@~ ¦ QA_ ¦ QB@ ¦ QC! ¦ R!~ ¦ R"_ ¦ R#@ ¦ R$!
¦ 80819 ¦ P{~ ¦ P|_ ¦ P}@ ¦ P~! ¦ Q\~ ¦ Q]_ ¦ Q^@ ¦ Q_! ¦ R=~ ¦ R>_ ¦ R?@ ¦ R@! ¦ S!!
¦ 80850 ¦ P|~ ¦ P}_ ¦ P~@ ¦ Q]~ ¦ Q^_ ¦ Q_@ ¦ Q`! ¦ R>~ ¦ R?_ ¦ R@@ ¦ RA! ¦ S!@ ¦ S"!
¦ 80881 ¦ P}~ ¦ P~_ ¦ Q^~ ¦ Q__ ¦ Q`@ ¦ Qa! ¦ R?~ ¦ R@_ ¦ RA@ ¦ RB! ¦ S!_ ¦ S"@ ¦ S#!
¦ 80912 ¦ P~~ ¦ Q_~ ¦ Q`_ ¦ Qa@ ¦ Qb! ¦ R@~ ¦ RA_ ¦ RB@ ¦ RC! ¦ S!~ ¦ S"_ ¦ S#@ ¦ S$!
¦ 81780 ¦ Q{~ ¦ Q|_ ¦ Q}@ ¦ Q~! ¦ R\~ ¦ R]_ ¦ R^@ ¦ R_! ¦ S=~ ¦ S>_ ¦ S?@ ¦ S@! ¦ T!!
¦ 81811 ¦ Q|~ ¦ Q}_ ¦ Q~@ ¦ R]~ ¦ R^_ ¦ R_@ ¦ R`! ¦ S>~ ¦ S?_ ¦ S@@ ¦ SA! ¦ T!@ ¦ T"!
¦ 81842 ¦ Q}~ ¦ Q~_ ¦ R^~ ¦ R__ ¦ R`@ ¦ Ra! ¦ S?~ ¦ S@_ ¦ SA@ ¦ SB! ¦ T!_ ¦ T"@ ¦ T#!
¦ 81873 ¦ Q~~ ¦ R_~ ¦ R`_ ¦ Ra@ ¦ Rb! ¦ S@~ ¦ SA_ ¦ SB@ ¦ SC! ¦ T!~ ¦ T"_ ¦ T#@ ¦ T$!
¦ 82741 ¦ R{~ ¦ R|_ ¦ R}@ ¦ R~! ¦ S\~ ¦ S]_ ¦ S^@ ¦ S_! ¦ T=~ ¦ T>_ ¦ T?@ ¦ T@! ¦ U!!
¦ 82772 ¦ R|~ ¦ R}_ ¦ R~@ ¦ S]~ ¦ S^_ ¦ S_@ ¦ S`! ¦ T>~ ¦ T?_ ¦ T@@ ¦ TA! ¦ U!@ ¦ U"!
¦ 82803 ¦ R}~ ¦ R~_ ¦ S^~ ¦ S__ ¦ S`@ ¦ Sa! ¦ T?~ ¦ T@_ ¦ TA@ ¦ TB! ¦ U!_ ¦ U"@ ¦ U#!
¦ 82834 ¦ R~~ ¦ S_~ ¦ S`_ ¦ Sa@ ¦ Sb! ¦ T@~ ¦ TA_ ¦ TB@ ¦ TC! ¦ U!~ ¦ U"_ ¦ U#@ ¦ U$!
¦ 83702 ¦ S{~ ¦ S|_ ¦ S}@ ¦ S~! ¦ T\~ ¦ T]_ ¦ T^@ ¦ T_! ¦ U=~ ¦ U>_ ¦ U?@ ¦ U@! ¦ V!!
¦ 83733 ¦ S|~ ¦ S}_ ¦ S~@ ¦ T]~ ¦ T^_ ¦ T_@ ¦ T`! ¦ U>~ ¦ U?_ ¦ U@@ ¦ UA! ¦ V!@ ¦ V"!
¦ 83764 ¦ S}~ ¦ S~_ ¦ T^~ ¦ T__ ¦ T`@ ¦ Ta! ¦ U?~ ¦ U@_ ¦ UA@ ¦ UB! ¦ V!_ ¦ V"@ ¦ V#!
¦ 83795 ¦ S~~ ¦ T_~ ¦ T`_ ¦ Ta@ ¦ Tb! ¦ U@~ ¦ UA_ ¦ UB@ ¦ UC! ¦ V!~ ¦ V"_ ¦ V#@ ¦ V$!
¦ 84663 ¦ T{~ ¦ T|_ ¦ T}@ ¦ T~! ¦ U\~ ¦ U]_ ¦ U^@ ¦ U_! ¦ V=~ ¦ V>_ ¦ V?@ ¦ V@! ¦ W!!
¦ 84694 ¦ T|~ ¦ T}_ ¦ T~@ ¦ U]~ ¦ U^_ ¦ U_@ ¦ U`! ¦ V>~ ¦ V?_ ¦ V@@ ¦ VA! ¦ W!@ ¦ W"!
¦ 84725 ¦ T}~ ¦ T~_ ¦ U^~ ¦ U__ ¦ U`@ ¦ Ua! ¦ V?~ ¦ V@_ ¦ VA@ ¦ VB! ¦ W!_ ¦ W"@ ¦ W#!
¦ 84756 ¦ T~~ ¦ U_~ ¦ U`_ ¦ Ua@ ¦ Ub! ¦ V@~ ¦ VA_ ¦ VB@ ¦ VC! ¦ W!~ ¦ W"_ ¦ W#@ ¦ W$!
¦ 85624 ¦ U{~ ¦ U|_ ¦ U}@ ¦ U~! ¦ V\~ ¦ V]_ ¦ V^@ ¦ V_! ¦ W=~ ¦ W>_ ¦ W?@ ¦ W@! ¦ X!!
¦ 85655 ¦ U|~ ¦ U}_ ¦ U~@ ¦ V]~ ¦ V^_ ¦ V_@ ¦ V`! ¦ W>~ ¦ W?_ ¦ W@@ ¦ WA! ¦ X!@ ¦ X"!
¦ 85686 ¦ U}~ ¦ U~_ ¦ V^~ ¦ V__ ¦ V`@ ¦ Va! ¦ W?~ ¦ W@_ ¦ WA@ ¦ WB! ¦ X!_ ¦ X"@ ¦ X#!
¦ 85717 ¦ U~~ ¦ V_~ ¦ V`_ ¦ Va@ ¦ Vb! ¦ W@~ ¦ WA_ ¦ WB@ ¦ WC! ¦ X!~ ¦ X"_ ¦ X#@ ¦ X$!
¦ 86585 ¦ V{~ ¦ V|_ ¦ V}@ ¦ V~! ¦ W\~ ¦ W]_ ¦ W^@ ¦ W_! ¦ X=~ ¦ X>_ ¦ X?@ ¦ X@! ¦ Y!!
¦ 86616 ¦ V|~ ¦ V}_ ¦ V~@ ¦ W]~ ¦ W^_ ¦ W_@ ¦ W`! ¦ X>~ ¦ X?_ ¦ X@@ ¦ XA! ¦ Y!@ ¦ Y"!
¦ 86647 ¦ V}~ ¦ V~_ ¦ W^~ ¦ W__ ¦ W`@ ¦ Wa! ¦ X?~ ¦ X@_ ¦ XA@ ¦ XB! ¦ Y!_ ¦ Y"@ ¦ Y#!
¦ 86678 ¦ V~~ ¦ W_~ ¦ W`_ ¦ Wa@ ¦ Wb! ¦ X@~ ¦ XA_ ¦ XB@ ¦ XC! ¦ Y!~ ¦ Y"_ ¦ Y#@ ¦ Y$!
¦ 87546 ¦ W{~ ¦ W|_ ¦ W}@ ¦ W~! ¦ X\~ ¦ X]_ ¦ X^@ ¦ X_! ¦ Y=~ ¦ Y>_ ¦ Y?@ ¦ Y@! ¦ Z!!
¦ 87577 ¦ W|~ ¦ W}_ ¦ W~@ ¦ X]~ ¦ X^_ ¦ X_@ ¦ X`! ¦ Y>~ ¦ Y?_ ¦ Y@@ ¦ YA! ¦ Z!@ ¦ Z"!
¦ 87608 ¦ W}~ ¦ W~_ ¦ X^~ ¦ X__ ¦ X`@ ¦ Xa! ¦ Y?~ ¦ Y@_ ¦ YA@ ¦ YB! ¦ Z!_ ¦ Z"@ ¦ Z#!
¦ 87639 ¦ W~~ ¦ X_~ ¦ X`_ ¦ Xa@ ¦ Xb! ¦ Y@~ ¦ YA_ ¦ YB@ ¦ YC! ¦ Z!~ ¦ Z"_ ¦ Z#@ ¦ Z$!
¦ 88507 ¦ X{~ ¦ X|_ ¦ X}@ ¦ X~! ¦ Y\~ ¦ Y]_ ¦ Y^@ ¦ Y_! ¦ Z=~ ¦ Z>_ ¦ Z?@ ¦ Z@! ¦ [!!
¦ 88538 ¦ X|~ ¦ X}_ ¦ X~@ ¦ Y]~ ¦ Y^_ ¦ Y_@ ¦ Y`! ¦ Z>~ ¦ Z?_ ¦ Z@@ ¦ ZA! ¦ [!@ ¦ ["!
¦ 88569 ¦ X}~ ¦ X~_ ¦ Y^~ ¦ Y__ ¦ Y`@ ¦ Ya! ¦ Z?~ ¦ Z@_ ¦ ZA@ ¦ ZB! ¦ [!_ ¦ ["@ ¦ [#!
¦ 88600 ¦ X~~ ¦ Y_~ ¦ Y`_ ¦ Ya@ ¦ Yb! ¦ Z@~ ¦ ZA_ ¦ ZB@ ¦ ZC! ¦ [!~ ¦ ["_ ¦ [#@ ¦ [$!
¦ 89468 ¦ Y{~ ¦ Y|_ ¦ Y}@ ¦ Y~! ¦ Z\~ ¦ Z]_ ¦ Z^@ ¦ Z_! ¦ [=~ ¦ [>_ ¦ [?@ ¦ [@! ¦ \!!
¦ 89499 ¦ Y|~ ¦ Y}_ ¦ Y~@ ¦ Z]~ ¦ Z^_ ¦ Z_@ ¦ Z`! ¦ [>~ ¦ [?_ ¦ [@@ ¦ [A! ¦ \!@ ¦ \"!
¦ 89530 ¦ Y}~ ¦ Y~_ ¦ Z^~ ¦ Z__ ¦ Z`@ ¦ Za! ¦ [?~ ¦ [@_ ¦ [A@ ¦ [B! ¦ \!_ ¦ \"@ ¦ \#!
¦ 89561 ¦ Y~~ ¦ Z_~ ¦ Z`_ ¦ Za@ ¦ Zb! ¦ [@~ ¦ [A_ ¦ [B@ ¦ [C! ¦ \!~ ¦ \"_ ¦ \#@ ¦ \$!
¦ 90429 ¦ Z{~ ¦ Z|_ ¦ Z}@ ¦ Z~! ¦ [\~ ¦ []_ ¦ [^@ ¦ [_! ¦ \=~ ¦ \>_ ¦ \?@ ¦ \@! ¦ ]!!
¦ 90460 ¦ Z|~ ¦ Z}_ ¦ Z~@ ¦ []~ ¦ [^_ ¦ [_@ ¦ [`! ¦ \>~ ¦ \?_ ¦ \@@ ¦ \A! ¦ ]!@ ¦ ]"!
¦ 90491 ¦ Z}~ ¦ Z~_ ¦ [^~ ¦ [__ ¦ [`@ ¦ [a! ¦ \?~ ¦ \@_ ¦ \A@ ¦ \B! ¦ ]!_ ¦ ]"@ ¦ ]#!
¦ 90522 ¦ Z~~ ¦ [_~ ¦ [`_ ¦ [a@ ¦ [b! ¦ \@~ ¦ \A_ ¦ \B@ ¦ \C! ¦ ]!~ ¦ ]"_ ¦ ]#@ ¦ ]$!
¦ 91390 ¦ [{~ ¦ [|_ ¦ [}@ ¦ [~! ¦ \\~ ¦ \]_ ¦ \^@ ¦ \_! ¦ ]=~ ¦ ]>_ ¦ ]?@ ¦ ]@! ¦ ^!!
¦ 91421 ¦ [|~ ¦ [}_ ¦ [~@ ¦ \]~ ¦ \^_ ¦ \_@ ¦ \`! ¦ ]>~ ¦ ]?_ ¦ ]@@ ¦ ]A! ¦ ^!@ ¦ ^"!
¦ 91452 ¦ [}~ ¦ [~_ ¦ \^~ ¦ \__ ¦ \`@ ¦ \a! ¦ ]?~ ¦ ]@_ ¦ ]A@ ¦ ]B! ¦ ^!_ ¦ ^"@ ¦ ^#!
¦ 91483 ¦ [~~ ¦ \_~ ¦ \`_ ¦ \a@ ¦ \b! ¦ ]@~ ¦ ]A_ ¦ ]B@ ¦ ]C! ¦ ^!~ ¦ ^"_ ¦ ^#@ ¦ ^$!
¦ 92351 ¦ \{~ ¦ \|_ ¦ \}@ ¦ \~! ¦ ]\~ ¦ ]]_ ¦ ]^@ ¦ ]_! ¦ ^=~ ¦ ^>_ ¦ ^?@ ¦ ^@! ¦ _!!
¦ 92382 ¦ \|~ ¦ \}_ ¦ \~@ ¦ ]]~ ¦ ]^_ ¦ ]_@ ¦ ]`! ¦ ^>~ ¦ ^?_ ¦ ^@@ ¦ ^A! ¦ _!@ ¦ _"!
¦ 92413 ¦ \}~ ¦ \~_ ¦ ]^~ ¦ ]__ ¦ ]`@ ¦ ]a! ¦ ^?~ ¦ ^@_ ¦ ^A@ ¦ ^B! ¦ _!_ ¦ _"@ ¦ _#!
¦ 92444 ¦ \~~ ¦ ]_~ ¦ ]`_ ¦ ]a@ ¦ ]b! ¦ ^@~ ¦ ^A_ ¦ ^B@ ¦ ^C! ¦ _!~ ¦ _"_ ¦ _#@ ¦ _$!
¦ 93312 ¦ ]{~ ¦ ]|_ ¦ ]}@ ¦ ]~! ¦ ^\~ ¦ ^]_ ¦ ^^@ ¦ ^_! ¦ _=~ ¦ _>_ ¦ _?@ ¦ _@! ¦ `!!
¦ 93343 ¦ ]|~ ¦ ]}_ ¦ ]~@ ¦ ^]~ ¦ ^^_ ¦ ^_@ ¦ ^`! ¦ _>~ ¦ _?_ ¦ _@@ ¦ _A! ¦ `!@ ¦ `"!
¦ 93374 ¦ ]}~ ¦ ]~_ ¦ ^^~ ¦ ^__ ¦ ^`@ ¦ ^a! ¦ _?~ ¦ _@_ ¦ _A@ ¦ _B! ¦ `!_ ¦ `"@ ¦ `#!
¦ 93405 ¦ ]~~ ¦ ^_~ ¦ ^`_ ¦ ^a@ ¦ ^b! ¦ _@~ ¦ _A_ ¦ _B@ ¦ _C! ¦ `!~ ¦ `"_ ¦ `#@ ¦ `$!
¦ 94273 ¦ ^{~ ¦ ^|_ ¦ ^}@ ¦ ^~! ¦ _\~ ¦ _]_ ¦ _^@ ¦ __! ¦ `=~ ¦ `>_ ¦ `?@ ¦ `@! ¦ a!!
¦ 94304 ¦ ^|~ ¦ ^}_ ¦ ^~@ ¦ _]~ ¦ _^_ ¦ __@ ¦ _`! ¦ `>~ ¦ `?_ ¦ `@@ ¦ `A! ¦ a!@ ¦ a"!
¦ 94335 ¦ ^}~ ¦ ^~_ ¦ _^~ ¦ ___ ¦ _`@ ¦ _a! ¦ `?~ ¦ `@_ ¦ `A@ ¦ `B! ¦ a!_ ¦ a"@ ¦ a#!
¦ 94366 ¦ ^~~ ¦ __~ ¦ _`_ ¦ _a@ ¦ _b! ¦ `@~ ¦ `A_ ¦ `B@ ¦ `C! ¦ a!~ ¦ a"_ ¦ a#@ ¦ a$!
¦ 95234 ¦ _{~ ¦ _|_ ¦ _}@ ¦ _~! ¦ `\~ ¦ `]_ ¦ `^@ ¦ `_! ¦ a=~ ¦ a>_ ¦ a?@ ¦ a@! ¦ b!!
¦ 95265 ¦ _|~ ¦ _}_ ¦ _~@ ¦ `]~ ¦ `^_ ¦ `_@ ¦ ``! ¦ a>~ ¦ a?_ ¦ a@@ ¦ aA! ¦ b!@ ¦ b"!
¦ 95296 ¦ _}~ ¦ _~_ ¦ `^~ ¦ `__ ¦ ``@ ¦ `a! ¦ a?~ ¦ a@_ ¦ aA@ ¦ aB! ¦ b!_ ¦ b"@ ¦ b#!
¦ 95327 ¦ _~~ ¦ `_~ ¦ ``_ ¦ `a@ ¦ `b! ¦ a@~ ¦ aA_ ¦ aB@ ¦ aC! ¦ b!~ ¦ b"_ ¦ b#@ ¦ b$!
¦ 96195 ¦ `{~ ¦ `|_ ¦ `}@ ¦ `~! ¦ a\~ ¦ a]_ ¦ a^@ ¦ a_! ¦ b=~ ¦ b>_ ¦ b?@ ¦ b@! ¦ c!!
¦ 96226 ¦ `|~ ¦ `}_ ¦ `~@ ¦ a]~ ¦ a^_ ¦ a_@ ¦ a`! ¦ b>~ ¦ b?_ ¦ b@@ ¦ bA! ¦ c!@ ¦ c"!
¦ 96257 ¦ `}~ ¦ `~_ ¦ a^~ ¦ a__ ¦ a`@ ¦ aa! ¦ b?~ ¦ b@_ ¦ bA@ ¦ bB! ¦ c!_ ¦ c"@ ¦ c#!
¦ 96288 ¦ `~~ ¦ a_~ ¦ a`_ ¦ aa@ ¦ ab! ¦ b@~ ¦ bA_ ¦ bB@ ¦ bC! ¦ c!~ ¦ c"_ ¦ c#@ ¦ c$!
¦ 97156 ¦ a{~ ¦ a|_ ¦ a}@ ¦ a~! ¦ b\~ ¦ b]_ ¦ b^@ ¦ b_! ¦ c=~ ¦ c>_ ¦ c?@ ¦ c@! ¦ d!!
¦ 97187 ¦ a|~ ¦ a}_ ¦ a~@ ¦ b]~ ¦ b^_ ¦ b_@ ¦ b`! ¦ c>~ ¦ c?_ ¦ c@@ ¦ cA! ¦ d!@ ¦ d"!
¦ 97218 ¦ a}~ ¦ a~_ ¦ b^~ ¦ b__ ¦ b`@ ¦ ba! ¦ c?~ ¦ c@_ ¦ cA@ ¦ cB! ¦ d!_ ¦ d"@ ¦ d#!
¦ 97249 ¦ a~~ ¦ b_~ ¦ b`_ ¦ ba@ ¦ bb! ¦ c@~ ¦ cA_ ¦ cB@ ¦ cC! ¦ d!~ ¦ d"_ ¦ d#@ ¦ d$!
¦ 98117 ¦ b{~ ¦ b|_ ¦ b}@ ¦ b~! ¦ c\~ ¦ c]_ ¦ c^@ ¦ c_! ¦ d=~ ¦ d>_ ¦ d?@ ¦ d@! ¦ e!!
¦ 98148 ¦ b|~ ¦ b}_ ¦ b~@ ¦ c]~ ¦ c^_ ¦ c_@ ¦ c`! ¦ d>~ ¦ d?_ ¦ d@@ ¦ dA! ¦ e!@ ¦ e"!
¦ 98179 ¦ b}~ ¦ b~_ ¦ c^~ ¦ c__ ¦ c`@ ¦ ca! ¦ d?~ ¦ d@_ ¦ dA@ ¦ dB! ¦ e!_ ¦ e"@ ¦ e#!
¦ 98210 ¦ b~~ ¦ c_~ ¦ c`_ ¦ ca@ ¦ cb! ¦ d@~ ¦ dA_ ¦ dB@ ¦ dC! ¦ e!~ ¦ e"_ ¦ e#@ ¦ e$!
¦ 99078 ¦ c{~ ¦ c|_ ¦ c}@ ¦ c~! ¦ d\~ ¦ d]_ ¦ d^@ ¦ d_! ¦ e=~ ¦ e>_ ¦ e?@ ¦ e@! ¦ f!!
¦ 99109 ¦ c|~ ¦ c}_ ¦ c~@ ¦ d]~ ¦ d^_ ¦ d_@ ¦ d`! ¦ e>~ ¦ e?_ ¦ e@@ ¦ eA! ¦ f!@ ¦ f"!
¦ 99140 ¦ c}~ ¦ c~_ ¦ d^~ ¦ d__ ¦ d`@ ¦ da! ¦ e?~ ¦ e@_ ¦ eA@ ¦ eB! ¦ f!_ ¦ f"@ ¦ f#!
¦ 99171 ¦ c~~ ¦ d_~ ¦ d`_ ¦ da@ ¦ db! ¦ e@~ ¦ eA_ ¦ eB@ ¦ eC! ¦ f!~ ¦ f"_ ¦ f#@ ¦ f$!
¦ 100039 ¦ d{~ ¦ d|_ ¦ d}@ ¦ d~! ¦ e\~ ¦ e]_ ¦ e^@ ¦ e_! ¦ f=~ ¦ f>_ ¦ f?@ ¦ f@! ¦ g!!
¦ 100070 ¦ d|~ ¦ d}_ ¦ d~@ ¦ e]~ ¦ e^_ ¦ e_@ ¦ e`! ¦ f>~ ¦ f?_ ¦ f@@ ¦ fA! ¦ g!@ ¦ g"!
¦ 100101 ¦ d}~ ¦ d~_ ¦ e^~ ¦ e__ ¦ e`@ ¦ ea! ¦ f?~ ¦ f@_ ¦ fA@ ¦ fB! ¦ g!_ ¦ g"@ ¦ g#!
¦ 100132 ¦ d~~ ¦ e_~ ¦ e`_ ¦ ea@ ¦ eb! ¦ f@~ ¦ fA_ ¦ fB@ ¦ fC! ¦ g!~ ¦ g"_ ¦ g#@ ¦ g$!
¦ 101000 ¦ e{~ ¦ e|_ ¦ e}@ ¦ e~! ¦ f\~ ¦ f]_ ¦ f^@ ¦ f_! ¦ g=~ ¦ g>_ ¦ g?@ ¦ g@! ¦ h!!
¦ 101031 ¦ e|~ ¦ e}_ ¦ e~@ ¦ f]~ ¦ f^_ ¦ f_@ ¦ f`! ¦ g>~ ¦ g?_ ¦ g@@ ¦ gA! ¦ h!@ ¦ h"!
¦ 101062 ¦ e}~ ¦ e~_ ¦ f^~ ¦ f__ ¦ f`@ ¦ fa! ¦ g?~ ¦ g@_ ¦ gA@ ¦ gB! ¦ h!_ ¦ h"@ ¦ h#!
¦ 101093 ¦ e~~ ¦ f_~ ¦ f`_ ¦ fa@ ¦ fb! ¦ g@~ ¦ gA_ ¦ gB@ ¦ gC! ¦ h!~ ¦ h"_ ¦ h#@ ¦ h$!
¦ 101961 ¦ f{~ ¦ f|_ ¦ f}@ ¦ f~! ¦ g\~ ¦ g]_ ¦ g^@ ¦ g_! ¦ h=~ ¦ h>_ ¦ h?@ ¦ h@! ¦ i!!
¦ 101992 ¦ f|~ ¦ f}_ ¦ f~@ ¦ g]~ ¦ g^_ ¦ g_@ ¦ g`! ¦ h>~ ¦ h?_ ¦ h@@ ¦ hA! ¦ i!@ ¦ i"!
¦ 102023 ¦ f}~ ¦ f~_ ¦ g^~ ¦ g__ ¦ g`@ ¦ ga! ¦ h?~ ¦ h@_ ¦ hA@ ¦ hB! ¦ i!_ ¦ i"@ ¦ i#!
¦ 102054 ¦ f~~ ¦ g_~ ¦ g`_ ¦ ga@ ¦ gb! ¦ h@~ ¦ hA_ ¦ hB@ ¦ hC! ¦ i!~ ¦ i"_ ¦ i#@ ¦ i$!
¦ 102922 ¦ g{~ ¦ g|_ ¦ g}@ ¦ g~! ¦ h\~ ¦ h]_ ¦ h^@ ¦ h_! ¦ i=~ ¦ i>_ ¦ i?@ ¦ i@! ¦ j!!
¦ 102953 ¦ g|~ ¦ g}_ ¦ g~@ ¦ h]~ ¦ h^_ ¦ h_@ ¦ h`! ¦ i>~ ¦ i?_ ¦ i@@ ¦ iA! ¦ j!@ ¦ j"!
¦ 102984 ¦ g}~ ¦ g~_ ¦ h^~ ¦ h__ ¦ h`@ ¦ ha! ¦ i?~ ¦ i@_ ¦ iA@ ¦ iB! ¦ j!_ ¦ j"@ ¦ j#!
¦ 103015 ¦ g~~ ¦ h_~ ¦ h`_ ¦ ha@ ¦ hb! ¦ i@~ ¦ iA_ ¦ iB@ ¦ iC! ¦ j!~ ¦ j"_ ¦ j#@ ¦ j$!
¦ 103883 ¦ h{~ ¦ h|_ ¦ h}@ ¦ h~! ¦ i\~ ¦ i]_ ¦ i^@ ¦ i_! ¦ j=~ ¦ j>_ ¦ j?@ ¦ j@! ¦ k!!
¦ 103914 ¦ h|~ ¦ h}_ ¦ h~@ ¦ i]~ ¦ i^_ ¦ i_@ ¦ i`! ¦ j>~ ¦ j?_ ¦ j@@ ¦ jA! ¦ k!@ ¦ k"!
¦ 103945 ¦ h}~ ¦ h~_ ¦ i^~ ¦ i__ ¦ i`@ ¦ ia! ¦ j?~ ¦ j@_ ¦ jA@ ¦ jB! ¦ k!_ ¦ k"@ ¦ k#!
¦ 103976 ¦ h~~ ¦ i_~ ¦ i`_ ¦ ia@ ¦ ib! ¦ j@~ ¦ jA_ ¦ jB@ ¦ jC! ¦ k!~ ¦ k"_ ¦ k#@ ¦ k$!
¦ 104844 ¦ i{~ ¦ i|_ ¦ i}@ ¦ i~! ¦ j\~ ¦ j]_ ¦ j^@ ¦ j_! ¦ k=~ ¦ k>_ ¦ k?@ ¦ k@! ¦ l!!
¦ 104875 ¦ i|~ ¦ i}_ ¦ i~@ ¦ j]~ ¦ j^_ ¦ j_@ ¦ j`! ¦ k>~ ¦ k?_ ¦ k@@ ¦ kA! ¦ l!@ ¦ l"!
¦ 104906 ¦ i}~ ¦ i~_ ¦ j^~ ¦ j__ ¦ j`@ ¦ ja! ¦ k?~ ¦ k@_ ¦ kA@ ¦ kB! ¦ l!_ ¦ l"@ ¦ l#!
¦ 104937 ¦ i~~ ¦ j_~ ¦ j`_ ¦ ja@ ¦ jb! ¦ k@~ ¦ kA_ ¦ kB@ ¦ kC! ¦ l!~ ¦ l"_ ¦ l#@ ¦ l$!
¦ 105805 ¦ j{~ ¦ j|_ ¦ j}@ ¦ j~! ¦ k\~ ¦ k]_ ¦ k^@ ¦ k_! ¦ l=~ ¦ l>_ ¦ l?@ ¦ l@! ¦ m!!
¦ 105836 ¦ j|~ ¦ j}_ ¦ j~@ ¦ k]~ ¦ k^_ ¦ k_@ ¦ k`! ¦ l>~ ¦ l?_ ¦ l@@ ¦ lA! ¦ m!@ ¦ m"!
¦ 105867 ¦ j}~ ¦ j~_ ¦ k^~ ¦ k__ ¦ k`@ ¦ ka! ¦ l?~ ¦ l@_ ¦ lA@ ¦ lB! ¦ m!_ ¦ m"@ ¦ m#!
¦ 105898 ¦ j~~ ¦ k_~ ¦ k`_ ¦ ka@ ¦ kb! ¦ l@~ ¦ lA_ ¦ lB@ ¦ lC! ¦ m!~ ¦ m"_ ¦ m#@ ¦ m$!
¦ 106766 ¦ k{~ ¦ k|_ ¦ k}@ ¦ k~! ¦ l\~ ¦ l]_ ¦ l^@ ¦ l_! ¦ m=~ ¦ m>_ ¦ m?@ ¦ m@! ¦ n!!
¦ 106797 ¦ k|~ ¦ k}_ ¦ k~@ ¦ l]~ ¦ l^_ ¦ l_@ ¦ l`! ¦ m>~ ¦ m?_ ¦ m@@ ¦ mA! ¦ n!@ ¦ n"!
¦ 106828 ¦ k}~ ¦ k~_ ¦ l^~ ¦ l__ ¦ l`@ ¦ la! ¦ m?~ ¦ m@_ ¦ mA@ ¦ mB! ¦ n!_ ¦ n"@ ¦ n#!
¦ 106859 ¦ k~~ ¦ l_~ ¦ l`_ ¦ la@ ¦ lb! ¦ m@~ ¦ mA_ ¦ mB@ ¦ mC! ¦ n!~ ¦ n"_ ¦ n#@ ¦ n$!
¦ 107727 ¦ l{~ ¦ l|_ ¦ l}@ ¦ l~! ¦ m\~ ¦ m]_ ¦ m^@ ¦ m_! ¦ n=~ ¦ n>_ ¦ n?@ ¦ n@! ¦ o!!
¦ 107758 ¦ l|~ ¦ l}_ ¦ l~@ ¦ m]~ ¦ m^_ ¦ m_@ ¦ m`! ¦ n>~ ¦ n?_ ¦ n@@ ¦ nA! ¦ o!@ ¦ o"!
¦ 107789 ¦ l}~ ¦ l~_ ¦ m^~ ¦ m__ ¦ m`@ ¦ ma! ¦ n?~ ¦ n@_ ¦ nA@ ¦ nB! ¦ o!_ ¦ o"@ ¦ o#!
¦ 107820 ¦ l~~ ¦ m_~ ¦ m`_ ¦ ma@ ¦ mb! ¦ n@~ ¦ nA_ ¦ nB@ ¦ nC! ¦ o!~ ¦ o"_ ¦ o#@ ¦ o$!
¦ 108688 ¦ m{~ ¦ m|_ ¦ m}@ ¦ m~! ¦ n\~ ¦ n]_ ¦ n^@ ¦ n_! ¦ o=~ ¦ o>_ ¦ o?@ ¦ o@! ¦ p!!
¦ 108719 ¦ m|~ ¦ m}_ ¦ m~@ ¦ n]~ ¦ n^_ ¦ n_@ ¦ n`! ¦ o>~ ¦ o?_ ¦ o@@ ¦ oA! ¦ p!@ ¦ p"!
¦ 108750 ¦ m}~ ¦ m~_ ¦ n^~ ¦ n__ ¦ n`@ ¦ na! ¦ o?~ ¦ o@_ ¦ oA@ ¦ oB! ¦ p!_ ¦ p"@ ¦ p#!
¦ 108781 ¦ m~~ ¦ n_~ ¦ n`_ ¦ na@ ¦ nb! ¦ o@~ ¦ oA_ ¦ oB@ ¦ oC! ¦ p!~ ¦ p"_ ¦ p#@ ¦ p$!
¦ 109649 ¦ n{~ ¦ n|_ ¦ n}@ ¦ n~! ¦ o\~ ¦ o]_ ¦ o^@ ¦ o_! ¦ p=~ ¦ p>_ ¦ p?@ ¦ p@! ¦ q!!
¦ 109680 ¦ n|~ ¦ n}_ ¦ n~@ ¦ o]~ ¦ o^_ ¦ o_@ ¦ o`! ¦ p>~ ¦ p?_ ¦ p@@ ¦ pA! ¦ q!@ ¦ q"!
¦ 109711 ¦ n}~ ¦ n~_ ¦ o^~ ¦ o__ ¦ o`@ ¦ oa! ¦ p?~ ¦ p@_ ¦ pA@ ¦ pB! ¦ q!_ ¦ q"@ ¦ q#!
¦ 109742 ¦ n~~ ¦ o_~ ¦ o`_ ¦ oa@ ¦ ob! ¦ p@~ ¦ pA_ ¦ pB@ ¦ pC! ¦ q!~ ¦ q"_ ¦ q#@ ¦ q$!
¦ 110610 ¦ o{~ ¦ o|_ ¦ o}@ ¦ o~! ¦ p\~ ¦ p]_ ¦ p^@ ¦ p_! ¦ q=~ ¦ q>_ ¦ q?@ ¦ q@! ¦ r!!
¦ 110641 ¦ o|~ ¦ o}_ ¦ o~@ ¦ p]~ ¦ p^_ ¦ p_@ ¦ p`! ¦ q>~ ¦ q?_ ¦ q@@ ¦ qA! ¦ r!@ ¦ r"!
¦ 110672 ¦ o}~ ¦ o~_ ¦ p^~ ¦ p__ ¦ p`@ ¦ pa! ¦ q?~ ¦ q@_ ¦ qA@ ¦ qB! ¦ r!_ ¦ r"@ ¦ r#!
¦ 110703 ¦ o~~ ¦ p_~ ¦ p`_ ¦ pa@ ¦ pb! ¦ q@~ ¦ qA_ ¦ qB@ ¦ qC! ¦ r!~ ¦ r"_ ¦ r#@ ¦ r$!
¦ 111571 ¦ p{~ ¦ p|_ ¦ p}@ ¦ p~! ¦ q\~ ¦ q]_ ¦ q^@ ¦ q_! ¦ r=~ ¦ r>_ ¦ r?@ ¦ r@! ¦ s!!
¦ 111602 ¦ p|~ ¦ p}_ ¦ p~@ ¦ q]~ ¦ q^_ ¦ q_@ ¦ q`! ¦ r>~ ¦ r?_ ¦ r@@ ¦ rA! ¦ s!@ ¦ s"!
¦ 111633 ¦ p}~ ¦ p~_ ¦ q^~ ¦ q__ ¦ q`@ ¦ qa! ¦ r?~ ¦ r@_ ¦ rA@ ¦ rB! ¦ s!_ ¦ s"@ ¦ s#!
¦ 111664 ¦ p~~ ¦ q_~ ¦ q`_ ¦ qa@ ¦ qb! ¦ r@~ ¦ rA_ ¦ rB@ ¦ rC! ¦ s!~ ¦ s"_ ¦ s#@ ¦ s$!
¦ 112532 ¦ q{~ ¦ q|_ ¦ q}@ ¦ q~! ¦ r\~ ¦ r]_ ¦ r^@ ¦ r_! ¦ s=~ ¦ s>_ ¦ s?@ ¦ s@! ¦ t!!
¦ 112563 ¦ q|~ ¦ q}_ ¦ q~@ ¦ r]~ ¦ r^_ ¦ r_@ ¦ r`! ¦ s>~ ¦ s?_ ¦ s@@ ¦ sA! ¦ t!@ ¦ t"!
¦ 112594 ¦ q}~ ¦ q~_ ¦ r^~ ¦ r__ ¦ r`@ ¦ ra! ¦ s?~ ¦ s@_ ¦ sA@ ¦ sB! ¦ t!_ ¦ t"@ ¦ t#!
¦ 112625 ¦ q~~ ¦ r_~ ¦ r`_ ¦ ra@ ¦ rb! ¦ s@~ ¦ sA_ ¦ sB@ ¦ sC! ¦ t!~ ¦ t"_ ¦ t#@ ¦ t$!
¦ 113493 ¦ r{~ ¦ r|_ ¦ r}@ ¦ r~! ¦ s\~ ¦ s]_ ¦ s^@ ¦ s_! ¦ t=~ ¦ t>_ ¦ t?@ ¦ t@! ¦ u!!
¦ 113524 ¦ r|~ ¦ r}_ ¦ r~@ ¦ s]~ ¦ s^_ ¦ s_@ ¦ s`! ¦ t>~ ¦ t?_ ¦ t@@ ¦ tA! ¦ u!@ ¦ u"!
¦ 113555 ¦ r}~ ¦ r~_ ¦ s^~ ¦ s__ ¦ s`@ ¦ sa! ¦ t?~ ¦ t@_ ¦ tA@ ¦ tB! ¦ u!_ ¦ u"@ ¦ u#!
¦ 113586 ¦ r~~ ¦ s_~ ¦ s`_ ¦ sa@ ¦ sb! ¦ t@~ ¦ tA_ ¦ tB@ ¦ tC! ¦ u!~ ¦ u"_ ¦ u#@ ¦ u$!
¦ 114454 ¦ s{~ ¦ s|_ ¦ s}@ ¦ s~! ¦ t\~ ¦ t]_ ¦ t^@ ¦ t_! ¦ u=~ ¦ u>_ ¦ u?@ ¦ u@! ¦ v!!
¦ 114485 ¦ s|~ ¦ s}_ ¦ s~@ ¦ t]~ ¦ t^_ ¦ t_@ ¦ t`! ¦ u>~ ¦ u?_ ¦ u@@ ¦ uA! ¦ v!@ ¦ v"!
¦ 114516 ¦ s}~ ¦ s~_ ¦ t^~ ¦ t__ ¦ t`@ ¦ ta! ¦ u?~ ¦ u@_ ¦ uA@ ¦ uB! ¦ v!_ ¦ v"@ ¦ v#!
¦ 114547 ¦ s~~ ¦ t_~ ¦ t`_ ¦ ta@ ¦ tb! ¦ u@~ ¦ uA_ ¦ uB@ ¦ uC! ¦ v!~ ¦ v"_ ¦ v#@ ¦ v$!
¦ 115415 ¦ t{~ ¦ t|_ ¦ t}@ ¦ t~! ¦ u\~ ¦ u]_ ¦ u^@ ¦ u_! ¦ v=~ ¦ v>_ ¦ v?@ ¦ v@! ¦ w!!
¦ 115446 ¦ t|~ ¦ t}_ ¦ t~@ ¦ u]~ ¦ u^_ ¦ u_@ ¦ u`! ¦ v>~ ¦ v?_ ¦ v@@ ¦ vA! ¦ w!@ ¦ w"!
¦ 115477 ¦ t}~ ¦ t~_ ¦ u^~ ¦ u__ ¦ u`@ ¦ ua! ¦ v?~ ¦ v@_ ¦ vA@ ¦ vB! ¦ w!_ ¦ w"@ ¦ w#!
¦ 115508 ¦ t~~ ¦ u_~ ¦ u`_ ¦ ua@ ¦ ub! ¦ v@~ ¦ vA_ ¦ vB@ ¦ vC! ¦ w!~ ¦ w"_ ¦ w#@ ¦ w$!
¦ 116376 ¦ u{~ ¦ u|_ ¦ u}@ ¦ u~! ¦ v\~ ¦ v]_ ¦ v^@ ¦ v_! ¦ w=~ ¦ w>_ ¦ w?@ ¦ w@! ¦ x!!
¦ 116407 ¦ u|~ ¦ u}_ ¦ u~@ ¦ v]~ ¦ v^_ ¦ v_@ ¦ v`! ¦ w>~ ¦ w?_ ¦ w@@ ¦ wA! ¦ x!@ ¦ x"!
¦ 116438 ¦ u}~ ¦ u~_ ¦ v^~ ¦ v__ ¦ v`@ ¦ va! ¦ w?~ ¦ w@_ ¦ wA@ ¦ wB! ¦ x!_ ¦ x"@ ¦ x#!
¦ 116469 ¦ u~~ ¦ v_~ ¦ v`_ ¦ va@ ¦ vb! ¦ w@~ ¦ wA_ ¦ wB@ ¦ wC! ¦ x!~ ¦ x"_ ¦ x#@ ¦ x$!
¦ 117337 ¦ v{~ ¦ v|_ ¦ v}@ ¦ v~! ¦ w\~ ¦ w]_ ¦ w^@ ¦ w_! ¦ x=~ ¦ x>_ ¦ x?@ ¦ x@! ¦ y!!
¦ 117368 ¦ v|~ ¦ v}_ ¦ v~@ ¦ w]~ ¦ w^_ ¦ w_@ ¦ w`! ¦ x>~ ¦ x?_ ¦ x@@ ¦ xA! ¦ y!@ ¦ y"!
¦ 117399 ¦ v}~ ¦ v~_ ¦ w^~ ¦ w__ ¦ w`@ ¦ wa! ¦ x?~ ¦ x@_ ¦ xA@ ¦ xB! ¦ y!_ ¦ y"@ ¦ y#!
¦ 117430 ¦ v~~ ¦ w_~ ¦ w`_ ¦ wa@ ¦ wb! ¦ x@~ ¦ xA_ ¦ xB@ ¦ xC! ¦ y!~ ¦ y"_ ¦ y#@ ¦ y$!
¦ 118298 ¦ w{~ ¦ w|_ ¦ w}@ ¦ w~! ¦ x\~ ¦ x]_ ¦ x^@ ¦ x_! ¦ y=~ ¦ y>_ ¦ y?@ ¦ y@! ¦ z!!
¦ 118329 ¦ w|~ ¦ w}_ ¦ w~@ ¦ x]~ ¦ x^_ ¦ x_@ ¦ x`! ¦ y>~ ¦ y?_ ¦ y@@ ¦ yA! ¦ z!@ ¦ z"!
¦ 118360 ¦ w}~ ¦ w~_ ¦ x^~ ¦ x__ ¦ x`@ ¦ xa! ¦ y?~ ¦ y@_ ¦ yA@ ¦ yB! ¦ z!_ ¦ z"@ ¦ z#!
¦ 118391 ¦ w~~ ¦ x_~ ¦ x`_ ¦ xa@ ¦ xb! ¦ y@~ ¦ yA_ ¦ yB@ ¦ yC! ¦ z!~ ¦ z"_ ¦ z#@ ¦ z$!
¦ 119259 ¦ x{~ ¦ x|_ ¦ x}@ ¦ x~! ¦ y\~ ¦ y]_ ¦ y^@ ¦ y_! ¦ z=~ ¦ z>_ ¦ z?@ ¦ z@! ¦ {!!
¦ 119290 ¦ x|~ ¦ x}_ ¦ x~@ ¦ y]~ ¦ y^_ ¦ y_@ ¦ y`! ¦ z>~ ¦ z?_ ¦ z@@ ¦ zA! ¦ {!@ ¦ {"!
¦ 119321 ¦ x}~ ¦ x~_ ¦ y^~ ¦ y__ ¦ y`@ ¦ ya! ¦ z?~ ¦ z@_ ¦ zA@ ¦ zB! ¦ {!_ ¦ {"@ ¦ {#!
¦ 119352 ¦ x~~ ¦ y_~ ¦ y`_ ¦ ya@ ¦ yb! ¦ z@~ ¦ zA_ ¦ zB@ ¦ zC! ¦ {!~ ¦ {"_ ¦ {#@ ¦ {$!
¦ 120220 ¦ y{~ ¦ y|_ ¦ y}@ ¦ y~! ¦ z\~ ¦ z]_ ¦ z^@ ¦ z_! ¦ {=~ ¦ {>_ ¦ {?@ ¦ {@! ¦ |!!
¦ 120251 ¦ y|~ ¦ y}_ ¦ y~@ ¦ z]~ ¦ z^_ ¦ z_@ ¦ z`! ¦ {>~ ¦ {?_ ¦ {@@ ¦ {A! ¦ |!@ ¦ |"!
¦ 120282 ¦ y}~ ¦ y~_ ¦ z^~ ¦ z__ ¦ z`@ ¦ za! ¦ {?~ ¦ {@_ ¦ {A@ ¦ {B! ¦ |!_ ¦ |"@ ¦ |#!
¦ 120313 ¦ y~~ ¦ z_~ ¦ z`_ ¦ za@ ¦ zb! ¦ {@~ ¦ {A_ ¦ {B@ ¦ {C! ¦ |!~ ¦ |"_ ¦ |#@ ¦ |$!
¦ 121181 ¦ z{~ ¦ z|_ ¦ z}@ ¦ z~! ¦ {\~ ¦ {]_ ¦ {^@ ¦ {_! ¦ |=~ ¦ |>_ ¦ |?@ ¦ |@! ¦ }!!
¦ 121212 ¦ z|~ ¦ z}_ ¦ z~@ ¦ {]~ ¦ {^_ ¦ {_@ ¦ {`! ¦ |>~ ¦ |?_ ¦ |@@ ¦ |A! ¦ }!@ ¦ }"!
¦ 121243 ¦ z}~ ¦ z~_ ¦ {^~ ¦ {__ ¦ {`@ ¦ {a! ¦ |?~ ¦ |@_ ¦ |A@ ¦ |B! ¦ }!_ ¦ }"@ ¦ }#!
¦ 121274 ¦ z~~ ¦ {_~ ¦ {`_ ¦ {a@ ¦ {b! ¦ |@~ ¦ |A_ ¦ |B@ ¦ |C! ¦ }!~ ¦ }"_ ¦ }#@ ¦ }$!
¦ 122142 ¦ {{~ ¦ {|_ ¦ {}@ ¦ {~! ¦ |\~ ¦ |]_ ¦ |^@ ¦ |_! ¦ }=~ ¦ }>_ ¦ }?@ ¦ }@! ¦ ~!!
¦ 122173 ¦ {|~ ¦ {}_ ¦ {~@ ¦ |]~ ¦ |^_ ¦ |_@ ¦ |`! ¦ }>~ ¦ }?_ ¦ }@@ ¦ }A! ¦ ~!@ ¦ ~"!
¦ 122204 ¦ {}~ ¦ {~_ ¦ |^~ ¦ |__ ¦ |`@ ¦ |a! ¦ }?~ ¦ }@_ ¦ }A@ ¦ }B! ¦ ~!_ ¦ ~"@ ¦ ~#!
¦ 122235 ¦ {~~ ¦ |_~ ¦ |`_ ¦ |a@ ¦ |b! ¦ }@~ ¦ }A_ ¦ }B@ ¦ }C! ¦ ~!~ ¦ ~"_ ¦ ~#@ ¦ ~$!
|===

== Conclusion

No matter what hashing strategy is used, collisions are enevitable however some hashes are worse than others. You can expect String to be fairly poor.


// p.s. Sabrina is amazing.


